# Generated by Django 5.2.10 on 2026-03-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockLandRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parcel_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("registered_owner_name", models.CharField(max_length=255)),
                ("owner_id_number", models.CharField(max_length=20)),
                ("owner_kra_pin", models.CharField(blank=True, max_length=20)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("subcounty", models.CharField(blank=True, max_length=100)),
                ("registration_section", models.CharField(blank=True, max_length=150)),
                (
                    "search_reference_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("search_certificate_date", models.DateField(blank=True, null=True)),
                ("acreage_ha", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "land_type",
                    models.CharField(
                        choices=[("FREEHOLD", "Freehold"), ("LEASEHOLD", "Leasehold")],
                        max_length=20,
                    ),
                ),
                ("is_charged", models.BooleanField(default=False)),
                ("has_caution", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parcel_number"], name="registry_mo_parcel__7b0766_idx"
                    ),
                    models.Index(
                        fields=["registered_owner_name"],
                        name="registry_mo_registe_d05f8f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistryMismatchAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_number", models.CharField(db_index=True, max_length=100)),
                ("provided_owner_name", models.CharField(blank=True, max_length=255)),
                ("provided_owner_id", models.CharField(blank=True, max_length=50)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parcel_number", "created_at"],
                        name="registry_mo_parcel__ca695b_idx",
                    )
                ],
            },
        ),
    ]
