# Generated by Django 5.2.10 on 2026-03-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry_mock", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mocklandregistry",
            new_name="registry_mo_parcel__7b0766_idx",
            old_name="registry_moc_parcel__9a0c45_idx",
        ),
        migrations.RenameIndex(
            model_name="mocklandregistry",
            new_name="registry_mo_registe_d05f8f_idx",
            old_name="registry_moc_registe_fa1c0c_idx",
        ),
    ]
