# Generated by Django 5.2.10 on 2026-03-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "registry_mock",
            "0003_merge_0002_registry_mismatch_attempt_0002_rename_registry_moc_parcel__9a0c45_idx_registry_mo_parcel__7b0766_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="registrymismatchattempt",
            new_name="registry_mo_parcel__ca695b_idx",
            old_name="registry_moc_parcel__0d3c4e_idx",
        ),
    ]
