# Generated by Django 5.2.10 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry_mock", "0004_rename_registry_moc_parcel__0d3c4e_idx_registry_mo_parcel__ca695b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="mocklandregistry",
            name="county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mocklandregistry",
            name="subcounty",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mocklandregistry",
            name="registration_section",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="mocklandregistry",
            name="search_reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mocklandregistry",
            name="search_certificate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
