# Generated by Django 4.2.29 on 2026-06-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_code", models.CharField(blank=True, max_length=20)),
                ("account_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=50)),
                ("branch_name", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="KES", max_length=10)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_bank_beneficiary",
                "ordering": ["legal_name", "bank_name", "account_name"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("purchase", "Purchase"), ("lease", "Lease")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("offer_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("lease_duration_months", models.IntegerField(blank=True, null=True)),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("lease_start_date", models.DateField(blank=True, null=True)),
                ("lease_end_date", models.DateField(blank=True, null=True)),
                ("offer_accepted_date", models.DateTimeField(blank=True, null=True)),
                ("due_diligence_date", models.DateTimeField(blank=True, null=True)),
                ("lcb_consent_date", models.DateTimeField(blank=True, null=True)),
                ("stamp_duty_date", models.DateTimeField(blank=True, null=True)),
                ("title_transfer_date", models.DateTimeField(blank=True, null=True)),
                ("final_payment_date", models.DateTimeField(blank=True, null=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("agreement_date", models.DateTimeField(blank=True, null=True)),
                ("handover_date", models.DateTimeField(blank=True, null=True)),
                ("lease_active_date", models.DateTimeField(blank=True, null=True)),
                ("offer_deadline", models.DateField(blank=True, null=True)),
                ("due_diligence_deadline", models.DateField(blank=True, null=True)),
                ("lcb_consent_deadline", models.DateField(blank=True, null=True)),
                ("stamp_duty_deadline", models.DateField(blank=True, null=True)),
                ("title_transfer_deadline", models.DateField(blank=True, null=True)),
                ("final_payment_deadline", models.DateField(blank=True, null=True)),
                ("completion_deadline", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("documents", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="listings.plot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("lease", "Lease"),
                            ("service", "Service"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("commitment_fee", "Commitment / Verification Fee"),
                            ("viewing_fee", "Viewing Fee"),
                            ("reservation_deposit", "Reservation Deposit"),
                            ("agreement_deposit", "Agreement Deposit"),
                            ("verification_package", "Verification Package"),
                            ("escrow_deposit", "Escrow Deposit"),
                            ("stamp_duty", "Stamp Duty"),
                            ("completion_balance", "Completion Balance"),
                            ("service_fee", "Service Fee"),
                        ],
                        default="viewing_fee",
                        max_length=40,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa_stk", "M-Pesa STK Push"),
                            ("mpesa_paybill", "M-Pesa Paybill / Till"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("airtel_money", "Airtel Money"),
                            ("wallet", "AgriPlot Wallet"),
                            ("manual_escrow", "Manual Escrow"),
                        ],
                        default="mpesa_stk",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("in_escrow", "In Escrow"),
                            ("partially_released", "Partially Released"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("escrow_enabled", models.BooleanField(default=True)),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                (
                    "internal_reference",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                ("lease_start_date", models.DateField(blank=True, null=True)),
                ("lease_end_date", models.DateField(blank=True, null=True)),
                ("intended_use", models.CharField(blank=True, max_length=180)),
                (
                    "lease_security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notice_period_days", models.PositiveIntegerField(default=90)),
                ("good_husbandry_required", models.BooleanField(default=True)),
                ("soil_exit_test_required", models.BooleanField(default=True)),
                ("subject_to_sale", models.BooleanField(default=False)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests",
                        to="listings.plot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "account_number",
                    models.CharField(
                        editable=False,
                        help_text="Format: AGP-WLT-XXXXXXXX (Auto-generated)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("pin_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("failed_pin_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_wallet",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit (Deposit/Incoming)"),
                            ("DEBIT", "Debit (Withdrawal/Outgoing)"),
                        ],
                        db_column="transaction_type",
                        default="CREDIT",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit (Deposit/Incoming)"),
                            ("DEBIT", "Debit (Withdrawal/Outgoing)"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success (Immutable)"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("FROZEN", "Frozen (Held)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card Payment"),
                            ("WALLET", "Internal Wallet Transfer"),
                            ("ESCROW", "Escrow Release"),
                            ("REFUND", "Refund"),
                            ("FEE", "Platform Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("mpesa_receipt", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        db_column="related_payment_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions_legacy",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "payments_wallet_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mpesa_stk", "M-Pesa STK Push"),
                            ("mpesa_paybill", "M-Pesa Paybill / Till"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("airtel_money", "Airtel Money"),
                            ("wallet", "AgriPlot Wallet"),
                            ("manual_escrow", "Manual Escrow"),
                        ],
                        default="mpesa_stk",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("bank_code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved (Ready for payout)"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled by User"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        blank=True,
                        db_column="transaction_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_request",
                        to="payments.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payments_wallet_withdrawal_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletDisbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "payment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_disbursements",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "recipient_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_disbursements",
                        to="payments.wallet",
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        blank=True,
                        db_column="transaction_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursement",
                        to="payments.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payments_wallet_disbursement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletDepositRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mpesa_stk", "M-Pesa STK Push"),
                            ("mpesa_paybill", "M-Pesa Paybill / Till"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("airtel_money", "Airtel Money"),
                            ("wallet", "AgriPlot Wallet"),
                            ("manual_escrow", "Manual Escrow"),
                        ],
                        default="mpesa_stk",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("checkout_url", models.URLField(blank=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        blank=True,
                        db_column="transaction_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_request",
                        to="payments.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payments_wallet_deposit_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("evidence_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=40)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("seller_no_show", "Seller No-show"),
                            ("missing_documents", "Missing Documents"),
                            ("payment_not_recognized", "Payment Not Recognized"),
                            ("fraud_signal", "Fraud Signal"),
                            ("refund_request", "Refund Request"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_disputes_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDisbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("seller", "Seller / Landlord"),
                            ("agent", "Agent"),
                            ("platform", "AgriPlot"),
                            ("officer", "Officer / Professional"),
                            ("government", "Government / Registry / Tax"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=180)),
                (
                    "paid_by_side",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer / Tenant"),
                            ("seller", "Seller / Landlord"),
                            ("platform", "Platform"),
                            ("shared", "Shared / As agreed"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("held", "Held in Escrow"),
                            ("ready", "Ready for Release"),
                            ("released", "Released"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("release_trigger", models.TextField(blank=True)),
                ("stage_code", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentClosingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=180)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("document_name", models.CharField(blank=True, max_length=180)),
                ("guidance", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="payments/closing_docs/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("buyer_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("seller_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_reference_number",
                    models.CharField(blank=True, max_length=120),
                ),
                ("meeting_date", models.DateField(blank=True, null=True)),
                (
                    "official_market_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "assessed_stamp_duty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("original_title_received", models.BooleanField(default=False)),
                ("seller_id_copy_received", models.BooleanField(default=False)),
                ("transfer_forms_signed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_closing_steps_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_steps",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=180)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller / Landlord"),
                            ("both", "Buyer & Seller"),
                            ("internal", "Internal"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("issued", "Issued"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("installment", "Installment"),
                            ("final", "Final Payment"),
                            ("rent", "Rent"),
                            ("security_deposit", "Security Deposit"),
                            ("platform_fee", "Platform Fee"),
                            ("professional_fee", "Professional Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.deal",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaseWaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desired_start_date", models.DateField(blank=True, null=True)),
                ("desired_duration_months", models.PositiveIntegerField(default=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("converted", "Converted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_waitlist_entries",
                        to="listings.plot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscrowAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "released_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_account",
                        to="payments.deal",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beneficiary_name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_code", models.CharField(blank=True, max_length=20)),
                ("account_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "rail",
                    models.CharField(
                        choices=[
                            ("pesalink", "PesaLink"),
                            ("rtgs", "RTGS"),
                            ("eft", "EFT"),
                        ],
                        default="pesalink",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("jenga", "Equity Jenga"), ("manual", "Manual")],
                        default="jenga",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("submitted", "Submitted"),
                            ("processing", "Processing"),
                            ("settled", "Settled"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("callback_payload", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transfer_requests",
                        to="payments.bankbeneficiary",
                    ),
                ),
                (
                    "disbursement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transfer_request",
                        to="payments.paymentdisbursement",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transfer_requests",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "db_table": "payments_bank_transfer_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "-created_at"], name="payments_wa_wallet__4fbbfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["reference"], name="payments_wa_referen_1aa8e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["idempotency_key"], name="payments_wa_idempot_3f3649_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["status", "channel"], name="payments_wa_status_bb8f02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmilestone",
            unique_together={("payment", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentdisbursement",
            unique_together={("payment", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentclosingstep",
            unique_together={("payment", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentcertificate",
            unique_together={("payment", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="leasewaitlistentry",
            unique_together={("plot", "user")},
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["status", "rail"], name="payments_ba_status_e7d6de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["reference"], name="payments_ba_referen_df5eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["provider_reference"], name="payments_ba_provide_34d7ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["idempotency_key"], name="payments_ba_idempot_08088f_idx"
            ),
        ),
    ]
