# Generated by Django 4.2.29 on 2026-06-13 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="legal_transaction",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated legal transaction for conveyancing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_payment",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_requests",
                to="listings.plot",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_requests_as_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="stamp_duty_verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Finance/Legal admin who verified KRA receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_stamp_duty_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentmilestone",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="paymentdispute",
            name="opened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_disputes_opened",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentdispute",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="paymentdispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_disputes_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentdisbursement",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disbursements",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="paymentdisbursement",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_disbursements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentclosingstep",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_closing_steps_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentclosingstep",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="closing_steps",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="paymentcertificate",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="leasewaitlistentry",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_waitlist_entries",
                to="listings.plot",
            ),
        ),
        migrations.AddField(
            model_name="leasewaitlistentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="banktransferrequest",
            name="beneficiary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transfer_requests",
                to="payments.bankbeneficiary",
            ),
        ),
        migrations.AddField(
            model_name="banktransferrequest",
            name="disbursement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transfer_request",
                to="payments.paymentdisbursement",
            ),
        ),
        migrations.AddField(
            model_name="banktransferrequest",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transfer_requests",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="bankbeneficiary",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_beneficiaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "-created_at"], name="payments_wa_wallet__4fbbfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["reference"], name="payments_wa_referen_1aa8e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["idempotency_key"], name="payments_wa_idempot_3f3649_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["status", "channel"], name="payments_wa_status_bb8f02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmilestone",
            unique_together={("payment", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentdisbursement",
            unique_together={("payment", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentclosingstep",
            unique_together={("payment", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentcertificate",
            unique_together={("payment", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="leasewaitlistentry",
            unique_together={("plot", "user")},
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["status", "rail"], name="payments_ba_status_e7d6de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["reference"], name="payments_ba_referen_df5eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["provider_reference"], name="payments_ba_provide_34d7ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferrequest",
            index=models.Index(
                fields=["idempotency_key"], name="payments_ba_idempot_08088f_idx"
            ),
        ),
    ]
