# Generated by Django 4.2.29 on 2026-06-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentrequest_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("commitment_fee", "Commitment / Verification Fee"),
                    ("reservation_deposit", "Reservation Deposit"),
                    ("agreement_deposit", "Agreement Deposit"),
                    ("verification_package", "Verification Package"),
                    ("escrow_deposit", "Escrow Deposit"),
                    ("stamp_duty", "Stamp Duty"),
                    ("completion_balance", "Completion Balance"),
                    ("service_fee", "Service Fee"),
                ],
                default="commitment_fee",
                max_length=40,
            ),
        ),
    ]
