# Generated by Django 4.2.29 on 2026-06-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentrequest_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletdepositrequest",
            name="payment_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_deposits",
                to="payments.paymentrequest",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("lease", "Lease"),
                    ("both", "Purchase & Lease"),
                ],
                default="purchase",
                max_length=20,
            ),
        ),
    ]
