# Generated by Django 4.2.29 on 2026-06-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_walletdepositrequest_payment_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("commitment_fee", "Verification Fee"),
                    ("reservation_deposit", "Reservation Deposit"),
                    ("agreement_deposit", "10% Escrow Deposit"),
                    ("verification_package", "Verification Package"),
                    ("escrow_deposit", "Escrow Deposit"),
                    ("stamp_duty", "Stamp Duty"),
                    ("completion_balance", "90% Escrow Balance"),
                    ("service_fee", "Service Fee"),
                ],
                default="commitment_fee",
                max_length=40,
            ),
        ),
    ]
