# Generated by Django 5.2.10 on 2026-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_paymentclosingstep_evidence_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("commitment_fee", "Commitment / Verification Fee"),
                    ("viewing_fee", "Viewing Fee"),
                    ("reservation_deposit", "Reservation Deposit"),
                    ("agreement_deposit", "Agreement Deposit"),
                    ("verification_package", "Verification Package"),
                    ("escrow_deposit", "Escrow Deposit"),
                    ("stamp_duty", "Stamp Duty"),
                    ("completion_balance", "Completion Balance"),
                    ("service_fee", "Service Fee"),
                ],
                default="viewing_fee",
                max_length=40,
            ),
        ),
    ]
