# Generated by Django 5.2.10 on 2026-04-08 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_paymentrequest_lease_fields_and_waitlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=180)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller / Landlord"),
                            ("both", "Buyer & Seller"),
                            ("internal", "Internal"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("issued", "Issued"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("payment", "code")},
            },
        ),
        migrations.CreateModel(
            name="PaymentDisbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("seller", "Seller / Landlord"),
                            ("agent", "Agent"),
                            ("platform", "AgriPlot"),
                            ("officer", "Officer / Professional"),
                            ("government", "Government / Registry / Tax"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=180)),
                (
                    "paid_by_side",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer / Tenant"),
                            ("seller", "Seller / Landlord"),
                            ("platform", "Platform"),
                            ("shared", "Shared / As agreed"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("held", "Held in Escrow"),
                            ("ready", "Ready for Release"),
                            ("released", "Released"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("release_trigger", models.TextField(blank=True)),
                ("stage_code", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("payment", "code")},
            },
        ),
    ]
