# Generated by Django 4.2.29 on 2026-06-13 06:29

from django.db import migrations, models


def _sync_bank_transfer_request_schema(apps, schema_editor):
    """
    Make the bank transfer table match the current state when it exists.

    Some deployed databases have drifted and no longer contain the table, so we
    guard every direct SQL change here and treat the migration as a no-op for
    that portion when the table is absent.
    """
    table_name = "payments_bank_transfer_request"
    if table_name not in schema_editor.connection.introspection.table_names():
        return

    schema_editor.execute(
        'ALTER TABLE "payments_bank_transfer_request" DROP COLUMN IF EXISTS "initiated_by_id";'
    )
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS "payments_ba_status_e7d6de_idx" '
        'ON "payments_bank_transfer_request" ("status", "rail");'
    )
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS "payments_ba_referen_df5eef_idx" '
        'ON "payments_bank_transfer_request" ("reference");'
    )
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS "payments_ba_provide_34d7ea_idx" '
        'ON "payments_bank_transfer_request" ("provider_reference");'
    )
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS "payments_ba_idempot_08088f_idx" '
        'ON "payments_bank_transfer_request" ("idempotency_key");'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_banktransferrequest"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="banktransferrequest",
                    name="initiated_by",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _sync_bank_transfer_request_schema,
                    migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("commitment_fee", "Commitment / Verification Fee"),
                    ("reservation_deposit", "Reservation Deposit"),
                    ("agreement_deposit", "Agreement Deposit"),
                    ("verification_package", "Verification Package"),
                    ("escrow_deposit", "Escrow Deposit"),
                    ("stamp_duty", "Stamp Duty"),
                    ("completion_balance", "Completion Balance"),
                    ("service_fee", "Service Fee"),
                ],
                default="commitment_fee",
                max_length=40,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="banktransferrequest",
                    index=models.Index(fields=["status", "rail"], name="payments_ba_status_e7d6de_idx"),
                ),
                migrations.AddIndex(
                    model_name="banktransferrequest",
                    index=models.Index(fields=["reference"], name="payments_ba_referen_df5eef_idx"),
                ),
                migrations.AddIndex(
                    model_name="banktransferrequest",
                    index=models.Index(fields=["provider_reference"], name="payments_ba_provide_34d7ea_idx"),
                ),
                migrations.AddIndex(
                    model_name="banktransferrequest",
                    index=models.Index(fields=["idempotency_key"], name="payments_ba_idempot_08088f_idx"),
                ),
            ],
            database_operations=[],
        ),
    ]
