# Generated by Django 4.2.29 on 2026-06-01 06:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Government/Institution employee ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g., Agricultural Officer, Livestock Officer",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(default="Ministry of Agriculture", max_length=100),
                ),
                (
                    "station",
                    models.CharField(
                        help_text="Assigned location/office", max_length=200
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Academic and professional qualifications"
                    ),
                ),
                ("specializations", models.CharField(blank=True, max_length=300)),
                ("years_of_experience", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20)),
                ("office_address", models.TextField(blank=True)),
                (
                    "assigned_counties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of counties they can verify",
                        size=None,
                    ),
                ),
                ("max_daily_tasks", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "response_time_avg",
                    models.FloatField(
                        default=0, help_text="Average response time in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_officers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_extensionofficer",
            },
        ),
        migrations.CreateModel(
            name="LandSurveyor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("designation", models.CharField(max_length=100)),
                ("station", models.CharField(max_length=200)),
                ("qualifications", models.TextField()),
                ("years_of_experience", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20)),
                ("office_address", models.TextField(blank=True)),
                (
                    "practicing_certificate_expiry",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "assigned_counties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of counties they can verify",
                        size=None,
                    ),
                ),
                ("max_daily_tasks", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "response_time_avg",
                    models.FloatField(
                        default=0, help_text="Average response time in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_surveyor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_surveyors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_landsurveyor",
            },
        ),
        migrations.CreateModel(
            name="VerificationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("registry_search", "Registry Search"),
                            ("document_review", "Document Review"),
                            ("extension_review", "Extension Officer Review"),
                            ("surveyor_inspection", "Land Surveyor Inspection"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("confirm_by", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "benefit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("benefit_currency", models.CharField(default="KES", max_length=10)),
                (
                    "benefit_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("pending", "Pending"),
                            ("earned", "Earned"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("benefit_notes", models.TextField(blank=True)),
                ("benefit_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("approved", models.BooleanField(blank=True, null=True)),
                ("review_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_verification_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tasks",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "db_table": "listings_verificationtask",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("document_uploaded", "Documents Uploaded"),
                            ("api_verification_started", "API Verification Started"),
                            ("title_search_completed", "Title Search Completed"),
                            ("owner_verified", "Owner Identity Verified"),
                            ("encumbrance_check", "Encumbrance Check"),
                            (
                                "physical_location_verified",
                                "Physical Location Verified",
                            ),
                            ("admin_review", "Under Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="document_uploaded",
                        max_length=50,
                    ),
                ),
                ("stage_details", models.JSONField(blank=True, default=dict)),
                ("is_complete", models.BooleanField(default=False)),
                ("api_responses", models.JSONField(blank=True, default=list)),
                ("search_reference", models.CharField(blank=True, max_length=100)),
                (
                    "search_fee_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("document_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("api_started_at", models.DateTimeField(blank=True, null=True)),
                ("title_search_at", models.DateTimeField(blank=True, null=True)),
                ("owner_verified_at", models.DateTimeField(blank=True, null=True)),
                ("encumbrance_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "physical_location_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("admin_review_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Verification Statuses",
                "db_table": "listings_verificationstatus",
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_type", models.CharField(max_length=50)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="listings.plot",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_verificationlog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("title_deed", "Title Deed"),
                            ("official_search", "Official Search Certificate"),
                            ("landowner_id", "Landowner National ID"),
                            ("kra_pin", "KRA PIN Certificate"),
                            ("survey_map", "Survey Map / Mutation Form"),
                            ("rates_clearance", "Land Rates Clearance"),
                            ("rent_clearance", "Land Rent Clearance"),
                            ("spousal_consent", "Spousal Consent"),
                            ("survey_plan", "Survey Plan"),
                            ("lcb_consent", "LCB Consent"),
                            ("plupa1_form", "PLUPA 1 / PPA 1"),
                            ("consent_to_transfer", "Consent to Transfer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="verification_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_docs",
                        to="listings.plot",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_verificationdocument",
            },
        ),
        migrations.CreateModel(
            name="TitleSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_platform", models.CharField(max_length=50)),
                ("official_owner", models.CharField(max_length=200)),
                ("parcel_number", models.CharField(max_length=100)),
                ("encumbrances", models.TextField(blank=True, null=True)),
                (
                    "lease_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("search_date", models.DateField(blank=True, null=True)),
                (
                    "raw_response_file",
                    models.FileField(
                        blank=True, null=True, upload_to="search_responses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_result",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "db_table": "listings_titlesearchresult",
            },
        ),
        migrations.CreateModel(
            name="PlotVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted for Verification"),
                            ("document_check", "Document Check"),
                            ("title_search", "Title Search with Ardhisasa"),
                            ("physical_verification", "Physical Verification"),
                            ("admin_approval", "Admin Approval"),
                            ("approved", "Approved for Listing"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("stage_details", models.JSONField(default=dict)),
                ("api_responses", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("title_search_at", models.DateTimeField(blank=True, null=True)),
                ("admin_review_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_verified",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="verification.verificationstatus",
                    ),
                ),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "db_table": "listings_plotverification",
            },
        ),
        migrations.CreateModel(
            name="ExtensionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("weather_conditions", models.CharField(blank=True, max_length=100)),
                ("soil_ph_verified", models.FloatField(blank=True, null=True)),
                (
                    "soil_ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Measured soil pH",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("soil_classification", models.CharField(blank=True, max_length=50)),
                (
                    "soil_texture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                        ],
                        max_length=50,
                    ),
                ),
                ("soil_depth", models.CharField(blank=True, max_length=50)),
                (
                    "soil_drainage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("moderate", "Moderate"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "topography",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "Flat / Level"),
                            ("gentle", "Gentle Slope"),
                            ("steep", "Steep Slope"),
                            ("valley", "Valley / Bottom Land"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_land_use", models.TextField(blank=True)),
                ("existing_crops", models.TextField(blank=True)),
                (
                    "crop_health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pest_issues", models.TextField(blank=True)),
                ("disease_issues", models.TextField(blank=True)),
                ("water_source_verified", models.CharField(blank=True, max_length=100)),
                (
                    "water_sources_available",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated verified water sources, e.g. Borehole, River, Rain-fed only.",
                    ),
                ),
                (
                    "distance_to_tarmac_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "distance_to_market_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "water_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("irrigation_system", models.CharField(blank=True, max_length=100)),
                (
                    "irrigation_viability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High Viability"),
                            ("moderate", "Moderate Viability"),
                            ("not_viable", "Not Viable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "power_access",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site"),
                            ("within_100m", "Within 100m"),
                            ("offgrid", "Off-grid / Solar"),
                            ("none", "Not Available"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "zoning_status",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural"),
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed_use", "Mixed Use"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "lcb_approval_potential",
                    models.CharField(
                        choices=[
                            ("likely", "Likely"),
                            ("uncertain", "Uncertain"),
                            ("unlikely", "Unlikely"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="uncertain",
                        max_length=50,
                    ),
                ),
                ("lcb_zone", models.BooleanField(default=False)),
                ("project_feasibility_note", models.TextField(blank=True)),
                ("soil_analysis_notes", models.TextField(blank=True)),
                (
                    "soil_analysis_report",
                    models.FileField(
                        blank=True,
                        help_text="Official soil analysis report from the field or lab.",
                        null=True,
                        upload_to="documents/soil_analysis_reports/",
                    ),
                ),
                ("topography_summary", models.TextField(blank=True)),
                ("site_photos", models.JSONField(default=list)),
                ("recommended_crops", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
                (
                    "overall_suitability",
                    models.CharField(
                        choices=[
                            ("highly_suitable", "Highly Suitable"),
                            ("moderately_suitable", "Moderately Suitable"),
                            ("marginally_suitable", "Marginally Suitable"),
                            ("not_suitable", "Not Suitable"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_conditions", "Approve with Conditions"),
                            ("reject", "Reject"),
                            ("further_review", "Further Review Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comments", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="verification.extensionofficer",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_reports",
                        to="listings.plot",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_report",
                        to="verification.verificationtask",
                    ),
                ),
            ],
            options={
                "db_table": "listings_extensionreport",
            },
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("kra_pin", "KRA PIN"),
                            ("title_deed", "Title Deed"),
                            ("official_search", "Official Search"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                ("is_readable", models.BooleanField(blank=True, null=True)),
                ("is_not_expired", models.BooleanField(blank=True, null=True)),
                ("name_matches_user", models.BooleanField(blank=True, null=True)),
                ("all_names_match", models.BooleanField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("approved", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_verifications",
                        to="listings.plot",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_verifications",
                        to="verification.verificationtask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_documentverification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("boundary_confirmed", models.BooleanField(default=False)),
                ("acreage_confirmed", models.BooleanField(default=False)),
                ("encumbrances_found", models.BooleanField(default=False)),
                ("encumbrance_details", models.TextField(blank=True)),
                ("boundary_markers", models.TextField(blank=True)),
                (
                    "beacon_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "all_present_and_intact",
                                "All beacons present and intact",
                            ),
                            (
                                "beacons_missing",
                                "Some beacons missing (re-establishment required)",
                            ),
                            ("displaced", "Beacons displaced or tampered with"),
                            (
                                "boundary_dispute",
                                "Boundary dispute noted with adjacent plots",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "official_document_reference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rim", "Registry Index Map (RIM)"),
                            ("mutation", "Mutation Form"),
                            ("share_certificate_map", "Share Certificate Map"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "beacon_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/beacon_certificates/",
                    ),
                ),
                (
                    "mutation_form",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/mutation_forms/"
                    ),
                ),
                ("rim_map_sheet_no", models.CharField(blank=True, max_length=100)),
                (
                    "ground_acreage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "deed_area",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("variance_flagged", models.BooleanField(default=False)),
                (
                    "boundary_data_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload .geojson, .kml, or .shp field boundary data.",
                        null=True,
                        upload_to="documents/boundary_data/",
                    ),
                ),
                (
                    "boundary_report",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/boundary_reports/"
                    ),
                ),
                (
                    "signed_survey_plan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/signed_survey_plans/",
                    ),
                ),
                ("encroachment_found", models.BooleanField(default=False)),
                ("encroachment_details", models.TextField(blank=True)),
                ("lsb_license_number", models.CharField(blank=True, max_length=100)),
                (
                    "surveyor_license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("topography_notes", models.TextField(blank=True)),
                ("access_road", models.CharField(blank=True, max_length=200)),
                ("utilities_available", models.TextField(blank=True)),
                ("subdivision_required", models.BooleanField(default=False)),
                ("mutation_required", models.BooleanField(default=False)),
                ("price_realistic", models.BooleanField(default=True)),
                (
                    "suggested_price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "suggested_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_review_notes", models.TextField(blank=True)),
                ("surveyor_declaration", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_conditions", "Approve with Conditions"),
                            ("reject", "Reject"),
                            ("further_review", "Further Review Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveyor_reports",
                        to="listings.plot",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="verification.landsurveyor",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveyor_report",
                        to="verification.verificationtask",
                    ),
                ),
            ],
            options={
                "db_table": "listings_surveyorreport",
                "indexes": [
                    models.Index(
                        fields=["visit_date"], name="listings_su_visit_d_0f0638_idx"
                    ),
                    models.Index(
                        fields=["surveyor", "-submitted_at"],
                        name="listings_su_surveyo_ddf4c2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SoilReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pH",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "organic_matter_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nitrogen_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "phosphorus_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "potassium_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "sand_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "silt_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "clay_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ec_salinity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("lab_id", models.CharField(blank=True, default="", max_length=100)),
                ("sample_date", models.DateField(blank=True, null=True)),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/soil_reports/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("unverified", "Unverified"),
                            ("lab_verified", "Lab Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_reports",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "db_table": "listings_soilreport",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["pH"], name="listings_so_pH_19efd8_idx"),
                    models.Index(
                        fields=["organic_matter_pct"],
                        name="listings_so_organic_d92de8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="landsurveyor",
            index=models.Index(
                fields=["station"], name="listings_la_station_7e09fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landsurveyor",
            index=models.Index(
                fields=["is_active"], name="listings_la_is_acti_92866f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionreport",
            index=models.Index(
                fields=["visit_date"], name="listings_ex_visit_d_2aa2cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionreport",
            index=models.Index(
                fields=["officer", "-submitted_at"],
                name="listings_ex_officer_74adc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="extensionofficer",
            index=models.Index(
                fields=["station"], name="listings_ex_station_8f7800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionofficer",
            index=models.Index(
                fields=["is_active"], name="listings_ex_is_acti_6c1c67_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentverification",
            unique_together={("user", "document_type", "plot")},
        ),
    ]
