# Generated by Django 5.2.10 on 2026-03-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationstatus",
            options={"verbose_name_plural": "Verification Statuses"},
        ),
    ]
