# Generated by Django 4.2.29 on 2026-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0003_verificationtask_benefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="extensionreport",
            name="distance_to_market_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="distance_to_tarmac_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="irrigation_viability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high", "High Viability"),
                    ("moderate", "Moderate Viability"),
                    ("not_viable", "Not Viable"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="water_sources_available",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated verified water sources, e.g. Borehole, River, Rain-fed only.",
            ),
        ),
        migrations.AddField(
            model_name="landsurveyor",
            name="practicing_certificate_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="boundary_data_file",
            field=models.FileField(
                blank=True,
                help_text="Upload .geojson, .kml, or .shp field boundary data.",
                null=True,
                upload_to="documents/boundary_data/",
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="official_document_reference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rim", "Registry Index Map (RIM)"),
                    ("mutation", "Mutation Form"),
                    ("share_certificate_map", "Share Certificate Map"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="surveyor_declaration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="variance_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="extensionreport",
            name="power_access",
            field=models.CharField(
                choices=[
                    ("onsite", "On-site"),
                    ("within_100m", "Within 100m"),
                    ("offgrid", "Off-grid / Solar"),
                    ("none", "Not Available"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="extensionreport",
            name="topography",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Flat / Level"),
                    ("gentle", "Gentle Slope"),
                    ("steep", "Steep Slope"),
                    ("valley", "Valley / Bottom Land"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveyorreport",
            name="beacon_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_present", "All beacons present and intact"),
                    ("missing", "Some beacons missing (re-establishment required)"),
                    ("displaced", "Beacons displaced or tampered with"),
                    ("boundary_dispute", "Boundary dispute noted with adjacent plots"),
                ],
                max_length=50,
            ),
        ),
    ]
