# Generated by Django 4.2.29 on 2026-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CropProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "optimal_ph_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "optimal_ph_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "optimal_altitude_min_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "optimal_altitude_max_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "optimal_temperature_min_c",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "optimal_temperature_max_c",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "optimal_rainfall_min_mm",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "optimal_rainfall_max_mm",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ideal_soil_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated soil labels such as Red Volcanic, Loam, Sandy Loam.",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_topographies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated topography labels such as flat, gentle, valley.",
                        max_length=255,
                    ),
                ),
                (
                    "irrigation_requirement",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"],
                        name="crops_cropp_is_acti_6d9e76_idx",
                    )
                ],
            },
        ),
    ]
