# Generated by Django 5.2.10 on 2026-03-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceComparable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("area_acres", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                ("crop_type", models.CharField(blank=True, max_length=200)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("about", "About Us"),
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="MarketPriceBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural Land"),
                            ("residential", "Residential Plot"),
                            ("commercial", "Commercial Land"),
                            ("mixed_use", "Mixed Use"),
                            ("industrial", "Industrial Land"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("lease", "For Lease"),
                            ("both", "For Sale & Lease"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["county", "land_type", "listing_type"],
                        name="listings_ma_county_9348d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("subcounty", models.CharField(blank=True, max_length=100, null=True)),
                ("nearest_town", models.CharField(blank=True, max_length=150)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("freehold", "Freehold"),
                            ("leasehold", "Leasehold"),
                            ("government", "Government"),
                            ("community", "Community"),
                        ],
                        default="freehold",
                        max_length=20,
                    ),
                ),
                (
                    "tenure_details",
                    models.CharField(
                        blank=True,
                        help_text="Lease duration/expiry or tenure notes",
                        max_length=200,
                    ),
                ),
                ("encumbrances", models.BooleanField(default=False)),
                ("encumbrance_details", models.TextField(blank=True)),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("area", models.FloatField(help_text="Land area value")),
                (
                    "area_unit",
                    models.CharField(
                        choices=[("acres", "Acres"), ("hectares", "Hectares")],
                        default="acres",
                        help_text="Unit for the land area",
                        max_length=10,
                    ),
                ),
                (
                    "parcel_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Parcel/Title/LR number (e.g., REGISTRY/BLOCK/PARCEL or LR 1234/567)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_subdivision",
                    models.BooleanField(
                        default=False,
                        help_text="True when listing is for a portion of a larger parcel",
                    ),
                ),
                (
                    "original_parcel_number",
                    models.CharField(
                        blank=True,
                        help_text="Original parcel number when listing a subdivision",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "registration_section",
                    models.CharField(
                        blank=True,
                        help_text="Registration section / registry block (e.g., Nairobi/Block 10)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "search_certificate_date",
                    models.DateField(
                        blank=True,
                        help_text="Official search certificate date",
                        null=True,
                    ),
                ),
                (
                    "search_reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Official search reference number",
                        max_length=100,
                    ),
                ),
                (
                    "owner_full_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of registered owner as per title/search",
                        max_length=200,
                    ),
                ),
                (
                    "owner_id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID number of the registered owner",
                        max_length=50,
                    ),
                ),
                (
                    "owner_kra_pin_number",
                    models.CharField(
                        blank=True,
                        help_text="KRA PIN number of the registered owner",
                        max_length=20,
                    ),
                ),
                (
                    "registry_owner_name",
                    models.CharField(
                        blank=True,
                        help_text="Owner name fetched from registry",
                        max_length=255,
                    ),
                ),
                (
                    "registry_owner_id_number",
                    models.CharField(
                        blank=True,
                        help_text="Owner ID fetched from registry",
                        max_length=50,
                    ),
                ),
                (
                    "registry_owner_kra_pin",
                    models.CharField(
                        blank=True,
                        help_text="Owner KRA PIN fetched from registry",
                        max_length=50,
                    ),
                ),
                (
                    "registry_area_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Area (hectares) fetched from registry",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "registry_land_type",
                    models.CharField(
                        blank=True,
                        help_text="Title type fetched from registry (FREEHOLD/LEASEHOLD)",
                        max_length=20,
                    ),
                ),
                (
                    "registry_has_encumbrances",
                    models.BooleanField(
                        default=False,
                        help_text="Encumbrance status fetched from registry",
                    ),
                ),
                (
                    "spousal_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Spousal consent provided (if matrimonial property)",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("lease", "For Lease"),
                            ("both", "For Sale & Lease"),
                        ],
                        default="sale",
                        max_length=10,
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural Land"),
                            ("residential", "Residential Plot"),
                            ("commercial", "Commercial Land"),
                            ("mixed_use", "Mixed Use"),
                            ("industrial", "Industrial Land"),
                        ],
                        default="agricultural",
                        max_length=20,
                    ),
                ),
                ("land_use_description", models.TextField(blank=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_basis",
                    models.CharField(
                        choices=[
                            ("owner_set", "Owner-set price"),
                            ("agent_market", "Agent market analysis"),
                            ("valuation_report", "Professional valuation report"),
                            ("government_set", "Government-set price"),
                            ("negotiated", "Negotiated (market demand)"),
                        ],
                        default="owner_set",
                        max_length=30,
                    ),
                ),
                (
                    "valuation_report",
                    models.FileField(
                        blank=True,
                        help_text="Optional valuation report (PDF/Image)",
                        null=True,
                        upload_to="documents/valuation_reports/",
                    ),
                ),
                ("price_notes", models.TextField(blank=True)),
                ("is_price_negotiable", models.BooleanField(default=True)),
                (
                    "lease_price_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lease_price_yearly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lease_duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Month-to-Month"),
                            ("seasonal", "Seasonal (3-6 months)"),
                            ("1year", "1 Year"),
                            ("3years", "3 Years"),
                            ("5years", "5 Years"),
                            ("10years", "10 Years"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("lease_terms", models.TextField(blank=True)),
                (
                    "lease_basis",
                    models.CharField(
                        choices=[
                            ("owner_set", "Owner-set price"),
                            ("agent_market", "Agent market analysis"),
                            ("valuation_report", "Professional valuation report"),
                            ("government_set", "Government-set price"),
                            ("negotiated", "Negotiated (market demand)"),
                        ],
                        default="owner_set",
                        max_length=30,
                    ),
                ),
                (
                    "government_price_proof",
                    models.FileField(
                        blank=True,
                        help_text="Official notice/gazette for government-set price",
                        null=True,
                        upload_to="documents/government_price_proofs/",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("soil_type", models.CharField(blank=True, default="", max_length=100)),
                ("ph_level", models.FloatField(blank=True, null=True)),
                (
                    "crop_suitability",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("has_water", models.BooleanField(default=False)),
                (
                    "water_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("borehole", "Borehole"),
                            ("river", "River/Stream"),
                            ("rain", "Rain-fed"),
                            ("irrigation", "Irrigation System"),
                            ("none", "No Water Source"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("has_electricity", models.BooleanField(default=False)),
                (
                    "electricity_meter",
                    models.BooleanField(default=False, help_text="Has meter installed"),
                ),
                ("has_road_access", models.BooleanField(default=False)),
                (
                    "road_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tarmac", "Tarmac"),
                            ("murram", "Murram/Gravel"),
                            ("earth", "Earth Road"),
                            ("footpath", "Footpath Only"),
                            ("none", "No Access"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "road_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("has_buildings", models.BooleanField(default=False)),
                ("building_description", models.TextField(blank=True)),
                (
                    "fencing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Full Perimeter"),
                            ("partial", "Partial"),
                            ("none", "No Fencing"),
                            ("live", "Live Fence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "title_deed",
                    models.FileField(
                        blank=True,
                        help_text="Official title deed document",
                        null=True,
                        upload_to="documents/title_deeds/",
                    ),
                ),
                (
                    "survey_map",
                    models.FileField(
                        blank=True,
                        help_text="Survey map or mutation form",
                        null=True,
                        upload_to="documents/survey_maps/",
                    ),
                ),
                (
                    "spousal_consent_doc",
                    models.FileField(
                        blank=True,
                        help_text="Spousal consent document (if applicable)",
                        null=True,
                        upload_to="documents/spousal_consents/",
                    ),
                ),
                (
                    "soil_report",
                    models.FileField(
                        blank=True,
                        help_text="Soil test report (optional)",
                        null=True,
                        upload_to="documents/soil_reports/",
                    ),
                ),
                (
                    "official_search",
                    models.FileField(
                        blank=True,
                        help_text="Official land search certificate",
                        null=True,
                        upload_to="documents/official_searches/",
                    ),
                ),
                (
                    "rates_clearance",
                    models.FileField(
                        blank=True,
                        help_text="Land rates clearance certificate",
                        null=True,
                        upload_to="documents/rates_clearance/",
                    ),
                ),
                (
                    "rent_clearance",
                    models.FileField(
                        blank=True,
                        help_text="Land rent clearance certificate",
                        null=True,
                        upload_to="documents/rent_clearance/",
                    ),
                ),
                (
                    "lcb_consent_doc",
                    models.FileField(
                        blank=True,
                        help_text="Land Control Board consent (agricultural land)",
                        null=True,
                        upload_to="documents/lcb_consents/",
                    ),
                ),
                (
                    "plupa1_form",
                    models.FileField(
                        blank=True,
                        help_text="PLUPA 1 / PPA 1 approval form (subdivision or change of use)",
                        null=True,
                        upload_to="documents/plupa1_forms/",
                    ),
                ),
                (
                    "consent_to_transfer",
                    models.FileField(
                        blank=True,
                        help_text="Consent to transfer for leasehold land",
                        null=True,
                        upload_to="documents/consent_to_transfer/",
                    ),
                ),
                (
                    "landowner_id_doc",
                    models.FileField(
                        blank=True,
                        help_text="Landowner's national ID",
                        null=True,
                        upload_to="documents/landowner_ids/",
                    ),
                ),
                (
                    "kra_pin",
                    models.FileField(
                        blank=True,
                        help_text="KRA PIN certificate",
                        null=True,
                        upload_to="documents/kra_pins/",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude (e.g. -1.292066 for Nairobi)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude (e.g. 36.821946 for Nairobi)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("elevation_meters", models.IntegerField(blank=True, null=True)),
                ("climate_zone", models.CharField(blank=True, max_length=100)),
                ("is_protected_area", models.BooleanField(default=False)),
                ("special_features", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_registry_record", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.agent",
                    ),
                ),
                (
                    "landowner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.landownerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Inquiry"),
                            ("phone_request", "Phone Number Request"),
                            ("phone_view", "Phone Number Viewed"),
                            ("visit_request", "Site Visit Request"),
                            ("message", "Direct Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded", models.BooleanField(default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="accounts.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparableSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparables",
                        to="listings.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plot_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.plot",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_range_min",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_range_max",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("methodology", models.CharField(blank=True, max_length=200)),
                ("comparable_plots_used", models.IntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("landowner_accepted", models.BooleanField(blank=True, null=True)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_suggestions",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Viewing Scheduled"),
                            ("rejected", "Not Interested"),
                            ("accepted", "Accepted Offer"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_interests",
                        to="listings.plot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["-created_at"], name="listings_pl_created_f2d8b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["listing_type"], name="listings_pl_listing_8e4d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["land_type"], name="listings_pl_land_ty_cdb482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["soil_type"], name="listings_pl_soil_ty_67a1b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["latitude", "longitude"], name="listings_pl_latitud_549932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["-created_at"], name="listings_co_created_1e8679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["responded"], name="listings_co_respond_1ec27a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinterest",
            unique_together={("user", "plot")},
        ),
    ]
