# Generated by Django 5.2.10 on 2026-03-05 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("template", models.CharField(max_length=100)),
                ("context", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceComparable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("area_acres", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                ("crop_type", models.CharField(blank=True, max_length=200)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("about", "About Us"),
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("textsms", "TextSMS")],
                        default="textsms",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
                ("message", models.TextField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("message_id", models.CharField(blank=True, max_length=100)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="",
                        help_text="Kindly provide your Phone Number",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Professional license number",
                        max_length=100,
                    ),
                ),
                (
                    "license_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_licenses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("id_number", models.CharField(help_text="National ID", max_length=20)),
                (
                    "kra_pin",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_kra/"
                    ),
                ),
                (
                    "practicing_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/practicing_certs/"
                    ),
                ),
                (
                    "good_conduct",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/good_conduct/"
                    ),
                ),
                (
                    "professional_indemnity",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/indemnity/"
                    ),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=100.0, help_text="Percentage of inquiries responded to"
                    ),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=24, help_text="Average response time in hours"
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("review_count", models.IntegerField(default=0)),
                ("total_listings", models.IntegerField(default=0)),
                ("verified_listings", models.IntegerField(default=0)),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("available_from", models.TimeField(default="09:00")),
                ("available_to", models.TimeField(default="17:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Government/Institution employee ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g., Agricultural Officer, Livestock Officer",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(default="Ministry of Agriculture", max_length=100),
                ),
                (
                    "station",
                    models.CharField(
                        help_text="Assigned location/office", max_length=200
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Academic and professional qualifications"
                    ),
                ),
                (
                    "specializations",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Crop Science, Soil Science",
                        max_length=300,
                    ),
                ),
                ("years_of_experience", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20)),
                ("office_address", models.TextField(blank=True)),
                (
                    "assigned_counties",
                    models.JSONField(
                        default=list, help_text="List of counties they can verify"
                    ),
                ),
                (
                    "max_daily_tasks",
                    models.IntegerField(default=5, help_text="Maximum tasks per day"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "response_time_avg",
                    models.FloatField(
                        default=0, help_text="Average response time in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_officers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImpersonationDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("duplicate_id", "Same ID multiple accounts"),
                            ("name_mismatch", "Name mismatch across documents"),
                            ("rapid_listings", "Too many listings too quickly"),
                            ("geographic_mismatch", "Listings far apart"),
                            ("content_similarity", "Listing description copied"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk - Block"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandownerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id",
                    models.FileField(
                        help_text="Upload a copy of your national ID",
                        upload_to="docs/national_ids/",
                    ),
                ),
                (
                    "kra_pin",
                    models.FileField(
                        help_text="Upload a copy of your KRA PIN",
                        upload_to="docs/kra_pins/",
                    ),
                ),
                (
                    "title_deed",
                    models.FileField(
                        blank=True,
                        help_text="Land title deed proving ownership (required for verification)",
                        null=True,
                        upload_to="docs/landowner_title_deeds/",
                    ),
                ),
                (
                    "land_search",
                    models.FileField(
                        blank=True,
                        help_text="Official land search certificate (ARDHI/Ardhisasa, validity ~3 months)",
                        null=True,
                        upload_to="docs/land_searches/",
                    ),
                ),
                (
                    "lcb_consent",
                    models.FileField(
                        blank=True,
                        help_text="Optional: Upload LCB consent if applicable",
                        null=True,
                        upload_to="docs/lcb_consents/",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if verification failed (allows re-submission)",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landowner_verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandSurveyor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g., Licensed Land Surveyor", max_length=100
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        help_text="Assigned location/office", max_length=200
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Academic and professional qualifications"
                    ),
                ),
                ("years_of_experience", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20)),
                ("office_address", models.TextField(blank=True)),
                (
                    "assigned_counties",
                    models.JSONField(
                        default=list, help_text="List of counties they can verify"
                    ),
                ),
                (
                    "max_daily_tasks",
                    models.IntegerField(default=5, help_text="Maximum tasks per day"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "response_time_avg",
                    models.FloatField(
                        default=0, help_text="Average response time in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_surveyor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_surveyors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketPriceBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural Land"),
                            ("residential", "Residential Plot"),
                            ("commercial", "Commercial Land"),
                            ("mixed_use", "Mixed Use"),
                            ("industrial", "Industrial Land"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("lease", "For Lease"),
                            ("both", "For Sale & Lease"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["county", "land_type", "listing_type"],
                        name="listings_ma_county_9348d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhoneEmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "phone_verification_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "email_verification_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("otp", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("verification", "Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("subcounty", models.CharField(blank=True, max_length=100, null=True)),
                ("nearest_town", models.CharField(blank=True, max_length=150)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("freehold", "Freehold"),
                            ("leasehold", "Leasehold"),
                            ("government", "Government"),
                            ("community", "Community"),
                        ],
                        default="freehold",
                        max_length=20,
                    ),
                ),
                (
                    "tenure_details",
                    models.CharField(
                        blank=True,
                        help_text="Lease duration/expiry or tenure notes",
                        max_length=200,
                    ),
                ),
                ("encumbrances", models.BooleanField(default=False)),
                ("encumbrance_details", models.TextField(blank=True)),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("area", models.FloatField(help_text="In acres or hectares")),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("lease", "For Lease"),
                            ("both", "For Sale & Lease"),
                        ],
                        default="sale",
                        max_length=10,
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural Land"),
                            ("residential", "Residential Plot"),
                            ("commercial", "Commercial Land"),
                            ("mixed_use", "Mixed Use"),
                            ("industrial", "Industrial Land"),
                        ],
                        default="agricultural",
                        max_length=20,
                    ),
                ),
                ("land_use_description", models.TextField(blank=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_basis",
                    models.CharField(
                        choices=[
                            ("owner_set", "Owner-set price"),
                            ("agent_market", "Agent market analysis"),
                            ("valuation_report", "Professional valuation report"),
                            ("government_set", "Government-set price"),
                            ("negotiated", "Negotiated (market demand)"),
                        ],
                        default="owner_set",
                        max_length=30,
                    ),
                ),
                (
                    "valuation_report",
                    models.FileField(
                        blank=True,
                        help_text="Optional valuation report (PDF/Image)",
                        null=True,
                        upload_to="documents/valuation_reports/",
                    ),
                ),
                (
                    "price_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on how price was determined (market trends, valuation, negotiations)",
                    ),
                ),
                ("is_price_negotiable", models.BooleanField(default=True)),
                (
                    "lease_price_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lease_price_yearly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lease_duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Month-to-Month"),
                            ("seasonal", "Seasonal (3-6 months)"),
                            ("1year", "1 Year"),
                            ("3years", "3 Years"),
                            ("5years", "5 Years"),
                            ("10years", "10 Years"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("lease_terms", models.TextField(blank=True)),
                (
                    "lease_basis",
                    models.CharField(
                        choices=[
                            ("owner_set", "Owner-set price"),
                            ("agent_market", "Agent market analysis"),
                            ("valuation_report", "Professional valuation report"),
                            ("government_set", "Government-set price"),
                            ("negotiated", "Negotiated (market demand)"),
                        ],
                        default="owner_set",
                        max_length=30,
                    ),
                ),
                (
                    "government_price_proof",
                    models.FileField(
                        blank=True,
                        help_text="Official notice/gazette for government-set price",
                        null=True,
                        upload_to="documents/government_price_proofs/",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("soil_type", models.CharField(blank=True, default="", max_length=100)),
                ("ph_level", models.FloatField(blank=True, null=True)),
                (
                    "crop_suitability",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("has_water", models.BooleanField(default=False)),
                (
                    "water_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("borehole", "Borehole"),
                            ("river", "River/Stream"),
                            ("rain", "Rain-fed"),
                            ("irrigation", "Irrigation System"),
                            ("none", "No Water Source"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("has_electricity", models.BooleanField(default=False)),
                (
                    "electricity_meter",
                    models.BooleanField(default=False, help_text="Has meter installed"),
                ),
                ("has_road_access", models.BooleanField(default=False)),
                (
                    "road_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tarmac", "Tarmac"),
                            ("murram", "Murram/Gravel"),
                            ("earth", "Earth Road"),
                            ("footpath", "Footpath Only"),
                            ("none", "No Access"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "road_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("has_buildings", models.BooleanField(default=False)),
                ("building_description", models.TextField(blank=True)),
                (
                    "fencing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Full Perimeter"),
                            ("partial", "Partial"),
                            ("none", "No Fencing"),
                            ("live", "Live Fence"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "title_deed",
                    models.FileField(
                        blank=True,
                        help_text="Official title deed document",
                        null=True,
                        upload_to="documents/title_deeds/",
                    ),
                ),
                (
                    "soil_report",
                    models.FileField(
                        blank=True,
                        help_text="Soil test report (optional)",
                        null=True,
                        upload_to="documents/soil_reports/",
                    ),
                ),
                (
                    "official_search",
                    models.FileField(
                        blank=True,
                        help_text="Official land search certificate",
                        null=True,
                        upload_to="documents/official_searches/",
                    ),
                ),
                (
                    "landowner_id_doc",
                    models.FileField(
                        blank=True,
                        help_text="Landowner's national ID",
                        null=True,
                        upload_to="documents/landowner_ids/",
                    ),
                ),
                (
                    "kra_pin",
                    models.FileField(
                        blank=True,
                        help_text="KRA PIN certificate",
                        null=True,
                        upload_to="documents/kra_pins/",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude (e.g. -1.292066 for Nairobi)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude (e.g. 36.821946 for Nairobi)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "elevation_meters",
                    models.IntegerField(
                        blank=True, help_text="Elevation in metres", null=True
                    ),
                ),
                ("climate_zone", models.CharField(blank=True, max_length=100)),
                (
                    "is_protected_area",
                    models.BooleanField(
                        default=False, help_text="Conservancy, forest reserve, etc."
                    ),
                ),
                (
                    "special_features",
                    models.TextField(
                        blank=True,
                        help_text="e.g., mature trees, water tank, scenic view",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.agent",
                    ),
                ),
                (
                    "landowner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.landownerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Inquiry"),
                            ("phone_request", "Phone Number Request"),
                            ("phone_view", "Phone Number Viewed"),
                            ("visit_request", "Site Visit Request"),
                            ("message", "Direct Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded", models.BooleanField(default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for admin use only",
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="listings.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparableSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Market source or reference",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparables",
                        to="listings.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plot_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.plot",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_range_min",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_range_max",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("methodology", models.CharField(blank=True, max_length=200)),
                ("comparable_plots_used", models.IntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("landowner_accepted", models.BooleanField(blank=True, null=True)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_suggestions",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("has_2fa_enabled", models.BooleanField(default=False)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("landowner", "Landowner"),
                            ("agent", "Agent"),
                            ("admin", "Administrator"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoilReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pH",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "organic_matter_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nitrogen_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "phosphorus_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "potassium_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "sand_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "silt_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "clay_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ec_salinity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("lab_id", models.CharField(blank=True, default="", max_length=100)),
                ("sample_date", models.DateField(blank=True, null=True)),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/soil_reports/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("unverified", "Unverified"),
                            ("lab_verified", "Lab Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_reports",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TitleSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_platform", models.CharField(max_length=50)),
                ("official_owner", models.CharField(max_length=200)),
                ("parcel_number", models.CharField(max_length=100)),
                ("encumbrances", models.TextField(blank=True, null=True)),
                (
                    "lease_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("search_date", models.DateField(blank=True, null=True)),
                (
                    "raw_response_file",
                    models.FileField(
                        blank=True, null=True, upload_to="search_responses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_result",
                        to="listings.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TwoFactorBackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "totp_secret",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Buyer's message or inquiry"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Viewing Scheduled"),
                            ("rejected", "Not Interested"),
                            ("accepted", "Accepted Offer"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes from agent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_interests",
                        to="listings.plot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("title_deed", "Title Deed"),
                            ("official_search", "Official Search Certificate"),
                            ("landowner_id", "Landowner National ID"),
                            ("kra_pin", "KRA PIN Certificate"),
                            ("survey_plan", "Survey Plan"),
                            ("rates_clearance", "Land Rates Clearance"),
                            ("lcb_consent", "LCB Consent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="verification_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_docs",
                        to="listings.plot",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_type", models.CharField(max_length=50)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="listings.plot",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("document_uploaded", "Documents Uploaded"),
                            ("api_verification_started", "API Verification Started"),
                            ("title_search_completed", "Title Search Completed"),
                            ("owner_verified", "Owner Identity Verified"),
                            ("encumbrance_check", "Encumbrance Check"),
                            (
                                "physical_location_verified",
                                "Physical Location Verified",
                            ),
                            ("admin_review", "Under Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="document_uploaded",
                        max_length=50,
                    ),
                ),
                ("stage_details", models.JSONField(blank=True, default=dict)),
                ("is_complete", models.BooleanField(default=False)),
                ("api_responses", models.JSONField(blank=True, default=list)),
                ("search_reference", models.CharField(blank=True, max_length=100)),
                (
                    "search_fee_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("document_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("api_started_at", models.DateTimeField(blank=True, null=True)),
                ("title_search_at", models.DateTimeField(blank=True, null=True)),
                ("owner_verified_at", models.DateTimeField(blank=True, null=True)),
                ("admin_review_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted for Verification"),
                            ("document_check", "Document Check"),
                            ("title_search", "Title Search with Ardhisasa"),
                            ("physical_verification", "Physical Verification"),
                            ("admin_approval", "Admin Approval"),
                            ("approved", "Approved for Listing"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("stage_details", models.JSONField(default=dict)),
                ("api_responses", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("title_search_at", models.DateTimeField(blank=True, null=True)),
                ("admin_review_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="listings.plot",
                    ),
                ),
                (
                    "owner_verified",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.verificationstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("document_review", "Document Review"),
                            ("extension_review", "Extension Officer Review"),
                            ("surveyor_inspection", "Land Surveyor Inspection"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("confirm_by", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("approved", models.BooleanField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_verification_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tasks",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("boundary_confirmed", models.BooleanField(default=False)),
                ("acreage_confirmed", models.BooleanField(default=False)),
                ("encumbrances_found", models.BooleanField(default=False)),
                ("encumbrance_details", models.TextField(blank=True)),
                (
                    "boundary_markers",
                    models.TextField(
                        blank=True,
                        help_text="Describe boundary markers or beacons found on site",
                    ),
                ),
                (
                    "topography_notes",
                    models.TextField(
                        blank=True,
                        help_text="Slope, terrain, drainage patterns, or obstacles",
                    ),
                ),
                (
                    "access_road",
                    models.CharField(
                        blank=True,
                        help_text="Describe road access and distance to main road",
                        max_length=200,
                    ),
                ),
                (
                    "utilities_available",
                    models.TextField(
                        blank=True,
                        help_text="Water, electricity, irrigation, other utilities",
                    ),
                ),
                ("subdivision_required", models.BooleanField(default=False)),
                ("mutation_required", models.BooleanField(default=False)),
                ("price_realistic", models.BooleanField(default=True)),
                (
                    "suggested_price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "suggested_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_review_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_conditions", "Approve with Conditions"),
                            ("reject", "Reject"),
                            ("further_review", "Further Review Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveyor_reports",
                        to="listings.plot",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="listings.landsurveyor",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveyor_report",
                        to="listings.verificationtask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_completed", "Task Completed"),
                            ("task_reminder", "Task Reminder"),
                            ("task_unconfirmed", "Task Unconfirmed"),
                            ("plot_submitted", "Plot Submitted"),
                            ("plot_approved", "Plot Approved"),
                            ("plot_rejected", "Plot Rejected"),
                            ("plot_stage_update", "Plot Stage Update"),
                            ("changes_requested", "Changes Requested"),
                            ("document_uploaded", "Document Uploaded"),
                            ("verification_started", "Verification Started"),
                            ("verification_completed", "Verification Completed"),
                            ("verification_step_update", "Verification Step Update"),
                            ("no_officer_available", "No Officer Available"),
                            ("role_request", "Role Request"),
                            ("role_approved", "Role Approved"),
                            ("account_verified", "Account Verified"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="listings.plot",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="listings.verificationtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("weather_conditions", models.CharField(blank=True, max_length=100)),
                ("soil_ph_verified", models.FloatField(blank=True, null=True)),
                (
                    "soil_texture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "soil_depth",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Deep (>50cm), Medium (25-50cm), Shallow (<25cm)",
                        max_length=50,
                    ),
                ),
                (
                    "soil_drainage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("moderate", "Moderate"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "existing_crops",
                    models.TextField(blank=True, help_text="Crops currently growing"),
                ),
                (
                    "crop_health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pest_issues", models.TextField(blank=True)),
                ("disease_issues", models.TextField(blank=True)),
                ("water_source_verified", models.CharField(blank=True, max_length=100)),
                (
                    "water_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("irrigation_system", models.CharField(blank=True, max_length=100)),
                (
                    "site_photos",
                    models.JSONField(default=list, help_text="List of photo URLs"),
                ),
                ("recommended_crops", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
                (
                    "overall_suitability",
                    models.CharField(
                        choices=[
                            ("highly_suitable", "Highly Suitable"),
                            ("moderately_suitable", "Moderately Suitable"),
                            ("marginally_suitable", "Marginally Suitable"),
                            ("not_suitable", "Not Suitable"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_conditions", "Approve with Conditions"),
                            ("reject", "Reject"),
                            ("further_review", "Further Review Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comments", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="listings.extensionofficer",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_reports",
                        to="listings.plot",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_report",
                        to="listings.verificationtask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("kra_pin", "KRA PIN"),
                            ("title_deed", "Title Deed"),
                            ("official_search", "Official Search"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                ("is_readable", models.BooleanField(blank=True, null=True)),
                ("is_not_expired", models.BooleanField(blank=True, null=True)),
                ("name_matches_user", models.BooleanField(blank=True, null=True)),
                ("all_names_match", models.BooleanField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("approved", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_verifications",
                        to="listings.plot",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_verifications",
                        to="listings.verificationtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_plot", "Create Listing"),
                            ("edit_plot", "Edit Listing"),
                            ("delete_plot", "Delete Listing"),
                            ("verify_landowner", "Verify Landowner"),
                            ("reject_landowner", "Reject Landowner"),
                            ("verify_agent", "Verify Agent"),
                            ("verify_plot", "Verify Plot"),
                            ("reject_plot", "Reject Plot"),
                            ("change_price", "Change Price"),
                            ("login", "Login"),
                            ("failed_login", "Failed Login"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="listings_au_created_586adf_idx"
                    ),
                    models.Index(
                        fields=["user", "action"], name="listings_au_user_id_f2005d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("verification", "Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "otp", "expires_at"],
                        name="listings_em_email_c7b849_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="extensionofficer",
            index=models.Index(
                fields=["station"], name="listings_ex_station_8f7800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionofficer",
            index=models.Index(
                fields=["is_active"], name="listings_ex_is_acti_6c1c67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impersonationdetection",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="listings_im_severit_a0c7ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landsurveyor",
            index=models.Index(
                fields=["station"], name="listings_la_station_7e09fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landsurveyor",
            index=models.Index(
                fields=["is_active"], name="listings_la_is_acti_92866f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phoneotp",
            index=models.Index(
                fields=["phone", "otp", "expires_at"],
                name="listings_ph_phone_464750_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["-created_at"], name="listings_pl_created_f2d8b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["listing_type"], name="listings_pl_listing_8e4d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["land_type"], name="listings_pl_land_ty_cdb482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["soil_type"], name="listings_pl_soil_ty_67a1b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["latitude", "longitude"], name="listings_pl_latitud_549932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["-created_at"], name="listings_co_created_1e8679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["responded"], name="listings_co_respond_1ec27a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilreport",
            index=models.Index(fields=["pH"], name="listings_so_pH_19efd8_idx"),
        ),
        migrations.AddIndex(
            model_name="soilreport",
            index=models.Index(
                fields=["organic_matter_pct"], name="listings_so_organic_d92de8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinterest",
            unique_together={("user", "plot")},
        ),
        migrations.AlterUniqueTogether(
            name="verificationstatus",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="surveyorreport",
            index=models.Index(
                fields=["visit_date"], name="listings_su_visit_d_0f0638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyorreport",
            index=models.Index(
                fields=["surveyor", "-submitted_at"],
                name="listings_su_surveyo_ddf4c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="listings_no_user_id_b01cc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="listings_no_user_id_ce5e26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionreport",
            index=models.Index(
                fields=["visit_date"], name="listings_ex_visit_d_2aa2cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionreport",
            index=models.Index(
                fields=["officer", "-submitted_at"],
                name="listings_ex_officer_74adc6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentverification",
            unique_together={("user", "document_type", "plot")},
        ),
    ]
