# Generated by Django 6.0.1 on 2026-01-30 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="soil_report",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/soil_reports/"
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="title_deed",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/title_deeds/"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_broker", models.BooleanField(default=False)),
                ("is_buyer", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
