# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="parcel_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Parcel/Title/LR number (e.g., REGISTRY/BLOCK/PARCEL or LR 1234/567)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="registration_section",
            field=models.CharField(
                blank=True,
                help_text="Registration section / registry block (e.g., Nairobi/Block 10)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="survey_map",
            field=models.FileField(
                blank=True,
                help_text="Survey map or mutation form",
                null=True,
                upload_to="documents/survey_maps/",
            ),
        ),
    ]

