# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_add_parcel_registration_survey_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="area_unit",
            field=models.CharField(
                choices=[("acres", "Acres"), ("hectares", "Hectares")],
                default="acres",
                help_text="Unit for the land area",
                max_length=10,
            ),
        ),
    ]

