# Generated by Django 5.2.10 on 2026-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_add_parcel_registration_survey_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="area",
            field=models.FloatField(
                help_text="Land area (acres; if using hectares, convert or note in listing)"
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("title_deed", "Title Deed"),
                    ("official_search", "Official Search Certificate"),
                    ("landowner_id", "Landowner National ID"),
                    ("kra_pin", "KRA PIN Certificate"),
                    ("survey_map", "Survey Map / Mutation Form"),
                    ("survey_plan", "Survey Plan"),
                    ("rates_clearance", "Land Rates Clearance"),
                    ("lcb_consent", "LCB Consent"),
                ],
                max_length=30,
            ),
        ),
    ]
