# Generated by Django 6.0 on 2026-01-31 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_plot_soil_report_plot_title_deed_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="verified",
        ),
        migrations.CreateModel(
            name="PlotVerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("in_review", "In Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_status",
                        to="listings.plot",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_plots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_id", models.CharField(max_length=50)),
                ("kra_pin", models.CharField(blank=True, max_length=40, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TitleSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_platform", models.CharField(max_length=50)),
                ("official_owner", models.CharField(max_length=200)),
                ("parcel_number", models.CharField(max_length=100)),
                ("encumbrances", models.TextField(blank=True, null=True)),
                (
                    "lease_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("search_date", models.DateField(blank=True, null=True)),
                (
                    "raw_response_file",
                    models.FileField(
                        blank=True, null=True, upload_to="search_responses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_result",
                        to="listings.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("title_deed", "Title Deed"),
                            ("survey_plan", "Survey Plan"),
                            ("official_search", "Official Search Certificate"),
                            ("seller_id", "Seller ID"),
                            ("land_rates", "Land Rates/Clearance"),
                            ("lcb_consent", "Land Control Board Consent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="verification_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_docs",
                        to="listings.plot",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
