# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_add_area_unit"),
        ("listings", "0003_alter_plot_area_alter_verificationdocument_doc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="area",
            field=models.FloatField(help_text="Land area value"),
        ),
    ]

