# Generated by Django 5.2.10 on 2026-02-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_plot_verified_plotverificationstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="license_doc",
            field=models.FileField(
                blank=True, null=True, upload_to="docs/broker_licenses/"
            ),
        ),
        migrations.AddField(
            model_name="broker",
            name="phone",
            field=models.CharField(
                default="", help_text="Kindly provide your Phone Number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="land_search",
            field=models.FileField(
                default="",
                help_text="Upload the official land search certificate",
                upload_to="docs/land_searches/",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="lcb_consent",
            field=models.FileField(
                blank=True,
                help_text="Optional: Upload LCB consent if applicable",
                null=True,
                upload_to="docs/lcb_consents/",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="title_deed",
            field=models.FileField(
                default="",
                help_text="Upload a copy of the title deed",
                upload_to="docs/title_deeds/",
            ),
        ),
        migrations.AlterField(
            model_name="broker",
            name="license_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Professional license number",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="kra_pin",
            field=models.FileField(
                default="",
                help_text="Upload a copy of the seller’s KRA PIN",
                upload_to="docs/kra_pins/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="national_id",
            field=models.FileField(
                default="",
                help_text="Upload a copy of the seller’s national ID",
                upload_to="docs/national_ids/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicator that this seller’s profile and documents are verified",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("title_deed", "Title Deed"),
                    ("official_search", "Official Search Certificate"),
                    ("seller_id", "Seller ID"),
                    ("kra_pin", "KRA PIN Certificate"),
                    ("survey_plan", "Survey Plan"),
                    ("rates_clearance", "Land Rates Clearance"),
                    ("lcb_consent", "LCB Consent (if required)"),
                ],
                max_length=30,
            ),
        ),
    ]
