# Generated by Django 5.2.10 on 2026-02-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_broker_license_doc_broker_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_broker",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_buyer",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="kra_pin",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the seller’s KRA PIN",
                null=True,
                upload_to="docs/kra_pins/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="national_id",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the seller’s national ID",
                null=True,
                upload_to="docs/national_ids/",
            ),
        ),
    ]
