# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_merge_0003_add_area_unit_0003_alter_plot_area_alter_verificationdocument_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="is_registry_record",
            field=models.BooleanField(
                default=False,
                help_text="Marks plots used as official registry records for land search testing",
            ),
        ),
    ]

