# Generated by Django 5.2.10 on 2026-04-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_plot_market_zone_price_guard"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="marketpriceband",
            name="listings_ma_county_9348d1_idx",
        ),
        migrations.AddIndex(
            model_name="marketpriceband",
            index=models.Index(
                fields=[
                    "county",
                    "subcounty",
                    "market_zone",
                    "land_type",
                    "listing_type",
                ],
                name="listings_ma_county_cba5bf_idx",
            ),
        ),
    ]
