# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_add_is_registry_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="owner_full_name",
            field=models.CharField(blank=True, help_text="Name of registered owner as per title/search", max_length=200),
        ),
        migrations.AddField(
            model_name="plot",
            name="owner_id_number",
            field=models.CharField(blank=True, help_text="National ID number of the registered owner", max_length=50),
        ),
        migrations.AddField(
            model_name="plot",
            name="spousal_consent",
            field=models.BooleanField(default=False, help_text="Spousal consent provided (if matrimonial property)"),
        ),
        migrations.AddField(
            model_name="plot",
            name="spousal_consent_doc",
            field=models.FileField(
                blank=True,
                help_text="Spousal consent document (if applicable)",
                null=True,
                upload_to="documents/spousal_consents/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="rates_clearance",
            field=models.FileField(
                blank=True,
                help_text="Land rates clearance certificate",
                null=True,
                upload_to="documents/rates_clearance/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="rent_clearance",
            field=models.FileField(
                blank=True,
                help_text="Land rent clearance certificate",
                null=True,
                upload_to="documents/rent_clearance/",
            ),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="zoning_status",
            field=models.CharField(
                choices=[
                    ("agricultural", "Agricultural"),
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("mixed_use", "Mixed Use"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="lcb_approval_potential",
            field=models.CharField(
                choices=[
                    ("likely", "Likely"),
                    ("uncertain", "Uncertain"),
                    ("unlikely", "Unlikely"),
                    ("not_applicable", "Not Applicable"),
                ],
                default="uncertain",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="project_feasibility_note",
            field=models.TextField(blank=True, help_text="Utilities, access, market viability"),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="soil_analysis_notes",
            field=models.TextField(blank=True, help_text="Soil analysis summary and constraints"),
        ),
        migrations.AddField(
            model_name="extensionreport",
            name="topography_summary",
            field=models.TextField(blank=True, help_text="Terrain, slope, drainage summary"),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="beacon_status",
            field=models.CharField(
                choices=[
                    ("intact", "Intact"),
                    ("missing", "Missing"),
                    ("displaced", "Displaced"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="beacon_certificate",
            field=models.FileField(
                blank=True,
                help_text="Beacon certificate (if issued)",
                null=True,
                upload_to="documents/beacon_certificates/",
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="rim_map_sheet_no",
            field=models.CharField(blank=True, help_text="RIM map sheet number", max_length=100),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="ground_acreage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Measured acreage on ground",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="boundary_report",
            field=models.FileField(
                blank=True,
                help_text="Boundary verification report",
                null=True,
                upload_to="documents/boundary_reports/",
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="surveyor_license_number",
            field=models.CharField(blank=True, help_text="Surveyor ISK license number", max_length=100),
        ),
    ]

