# Generated by Django 5.2.10 on 2026-02-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_remove_profile_is_broker_remove_profile_is_buyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified_broker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified_seller",
            field=models.BooleanField(default=False),
        ),
    ]
