# Generated by Django 5.2.10 on 2026-04-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_plot_ward_topography_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plot",
            new_name="listings_pl_county_c56d10_idx",
            old_name="listings_pl_county__cfd8ef_idx",
        ),
    ]
