# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_add_verification_form_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationstatus",
            name="encumbrance_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationstatus",
            name="physical_location_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

