# Generated by Django 5.2.10 on 2026-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_profile_is_verified_broker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="kra_pin",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the seller's KRA PIN",
                null=True,
                upload_to="docs/kra_pins/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="land_search",
            field=models.FileField(
                blank=True,
                help_text="Upload the official land search certificate",
                null=True,
                upload_to="docs/land_searches/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="national_id",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the seller's national ID",
                null=True,
                upload_to="docs/national_ids/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="title_deed",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the title deed",
                null=True,
                upload_to="docs/title_deeds/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
