# Generated by Django 5.2.10 on 2026-05-07 18:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_address_profile_intent_and_more"),
        (
            "listings",
            "0007_rename_listings_pl_county__cfd8ef_idx_listings_pl_county_c56d10_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("facility_type", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LandTransferAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_date", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="agreements/"),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "road_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tarmac", "Tarmac"),
                            ("murram", "Murram/Gravel"),
                            ("earth", "Earth Road"),
                            ("footpath", "Footpath Only"),
                            ("none", "No Access"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("level", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WaterSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="plot",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="plot",
            name="listings_pl_listing_8e4d7e_idx",
        ),
        migrations.RemoveIndex(
            model_name="plot",
            name="listings_pl_land_ty_cdb482_idx",
        ),
        migrations.RemoveIndex(
            model_name="plot",
            name="listings_pl_soil_ty_67a1b7_idx",
        ),
        migrations.RemoveIndex(
            model_name="plot",
            name="listings_pl_latitud_549932_idx",
        ),
        migrations.RemoveIndex(
            model_name="plot",
            name="listings_pl_county_c56d10_idx",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="climate_zone",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="elevation_meters",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="is_protected_area",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="special_features",
        ),
        migrations.AddField(
            model_name="plot",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="is_registry_record",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this plot has been verified against the land registry",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["market_status", "listing_type"],
                name="listings_pl_market__ee2c8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["county", "subcounty"], name="listings_pl_county_ee2bc7_idx"
            ),
        ),
        migrations.AddField(
            model_name="fraudreport",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_reports",
                to="listings.plot",
            ),
        ),
        migrations.AddField(
            model_name="fraudreport",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landtransferagreement",
            name="advocate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advocate_agreements",
                to="accounts.agent",
            ),
        ),
        migrations.AddField(
            model_name="landtransferagreement",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buying_agreements",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="landtransferagreement",
            name="lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lawyer_agreements",
                to="accounts.agent",
            ),
        ),
        migrations.AddField(
            model_name="landtransferagreement",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_agreements",
                to="listings.plot",
            ),
        ),
        migrations.AddField(
            model_name="landtransferagreement",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selling_agreements",
                to="accounts.landownerprofile",
            ),
        ),
    ]
