# Generated by Django 5.2.10 on 2026-05-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_fraudreport_healthfacility_landtransferagreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="is_registry_record",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this plot has been verified against the land registry",
            ),
        ),
    ]
