# Generated by Django 5.2.10 on 2026-02-05 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_plotimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotimage",
            name="caption",
        ),
        migrations.AddField(
            model_name="plot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="plotimage",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_list",
                to="listings.plot",
            ),
        ),
    ]
