# Generated by Django 5.2.10 on 2026-05-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_add_missing_fields"),
    ]

    operations = []
