# Generated by Django 5.2.10 on 2026-02-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_remove_plotimage_caption_plot_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="kra_pin",
            field=models.FileField(
                blank=True,
                help_text="KRA PIN certificate",
                null=True,
                upload_to="documents/kra_pins/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="official_search",
            field=models.FileField(
                blank=True,
                help_text="Official land search certificate",
                null=True,
                upload_to="documents/official_searches/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="seller_id",
            field=models.FileField(
                blank=True,
                help_text="Seller's national ID",
                null=True,
                upload_to="documents/seller_ids/",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="soil_report",
            field=models.FileField(
                blank=True,
                help_text="Soil test report (optional)",
                null=True,
                upload_to="documents/soil_reports/",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="title_deed",
            field=models.FileField(
                blank=True,
                help_text="Official title deed document",
                null=True,
                upload_to="documents/title_deeds/",
            ),
        ),
    ]
