# Generated by Django 5.2.10 on 2026-03-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_add_full_alignment_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyorreport",
            name="beacon_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_present", "All beacons present and intact"),
                    ("missing", "Some beacons missing (re-establishment required)"),
                    ("displaced", "Beacons displaced or tampered with"),
                ],
                max_length=50,
            ),
        ),
    ]
