# Generated by Django 5.2.10 on 2026-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_add_geom_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="special_features",
            field=models.TextField(
                blank=True,
                help_text="Special features of the land (e.g., water source, road access, fencing)",
            ),
        ),
    ]
