# Generated by Django 5.2.10 on 2026-05-08 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_plot_special_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landtransferagreement",
            options={
                "permissions": [
                    ("view_transfer", "Can view assigned client transfer documents"),
                    ("edit_transfer", "Can edit assigned client transfer documents"),
                ]
            },
        ),
        migrations.AddField(
            model_name="plot",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Hide this listing from public search results until it is reviewed.",
            ),
        ),
        migrations.CreateModel(
            name="UserPlotView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=1)),
                ("viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="listings.plot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "plot")},
            },
        ),
    ]
