# Generated by Django 5.2.10 on 2026-02-07 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_plot_kra_pin_plot_official_search_plot_seller_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="available_from",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="broker",
            name="available_to",
            field=models.TimeField(default="17:00"),
        ),
        migrations.AddField(
            model_name="broker",
            name="average_response_time",
            field=models.FloatField(
                default=24, help_text="Average response time in hours"
            ),
        ),
        migrations.AddField(
            model_name="broker",
            name="contact_preference",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "WhatsApp"),
                    ("any", "Any"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="broker",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="broker",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="broker",
            name="response_rate",
            field=models.FloatField(
                default=100.0, help_text="Percentage of inquiries responded to"
            ),
        ),
        migrations.AddField(
            model_name="broker",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="broker",
            name="total_listings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="broker",
            name="verified_listings",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Inquiry"),
                            ("phone_request", "Phone Number Request"),
                            ("phone_view", "Phone Number Viewed"),
                            ("visit_request", "Site Visit Request"),
                            ("message", "Direct Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded", models.BooleanField(default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="listings.broker",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="listings.plot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
