# Generated by Django 5.2.10 on 2026-02-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_broker_available_from_broker_available_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for admin use only", null=True
            ),
        ),
    ]
