# Generated by Codex on 2026-05-08

from django.db import migrations


def reconcile_listing_schema(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    model_names = [
        "WaterSource",
        "Road",
        "Market",
        "School",
        "HealthFacility",
        "LandTransferAgreement",
        "FraudReport",
        "UserPlotView",
    ]

    for model_name in model_names:
        model = apps.get_model("listings", model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(model._meta.db_table)

    plot_model = apps.get_model("listings", "Plot")
    plot_table = plot_model._meta.db_table
    plot_description = {
        col.name for col in connection.introspection.get_table_description(connection.cursor(), plot_table)
    }

    for field_name in ["geom", "special_features", "is_hidden"]:
        if field_name not in plot_description:
            schema_editor.add_field(plot_model, plot_model._meta.get_field(field_name))


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_alter_landtransferagreement_options_plot_is_hidden_and_more"),
    ]

    operations = [
        migrations.RunPython(reconcile_listing_schema, migrations.RunPython.noop),
    ]
