# Generated by Django 5.2.10 on 2026-02-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_contactrequest_admin_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pH",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "organic_matter_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nitrogen_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "phosphorus_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "potassium_mgkg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "sand_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "silt_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "clay_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ec_salinity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Electrical conductivity (dS/m)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("lab_id", models.CharField(blank=True, default="", max_length=100)),
                ("sample_date", models.DateField(blank=True, null=True)),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/soil_reports/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("unverified", "Unverified"),
                            ("lab_verified", "Lab Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_reports",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["pH"], name="listings_so_pH_19efd8_idx"),
                    models.Index(
                        fields=["organic_matter_pct"],
                        name="listings_so_organic_d92de8_idx",
                    ),
                ],
            },
        ),
    ]
