# Generated by Django 5.2.10 on 2026-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_switch_assigned_counties_to_arrayfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtask",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("registry_search", "Registry Search"),
                    ("document_review", "Document Review"),
                    ("extension_review", "Extension Officer Review"),
                    ("surveyor_inspection", "Land Surveyor Inspection"),
                ],
                max_length=30,
            ),
        ),
    ]
