# Generated by Django 5.2.10 on 2026-02-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_plotreaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broker",
            name="user",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified_landowner",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="",
                        help_text="Kindly provide your Phone Number",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Professional license number",
                        max_length=100,
                    ),
                ),
                (
                    "license_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_licenses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=100.0, help_text="Percentage of inquiries responded to"
                    ),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=24, help_text="Average response time in hours"
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("review_count", models.IntegerField(default=0)),
                ("total_listings", models.IntegerField(default=0)),
                ("verified_listings", models.IntegerField(default=0)),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("available_from", models.TimeField(default="09:00")),
                ("available_to", models.TimeField(default="17:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_requests",
                to="listings.agent",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.agent"
            ),
        ),
        migrations.CreateModel(
            name="LandownerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id",
                    models.FileField(
                        blank=True,
                        help_text="Upload a copy of the your national ID",
                        null=True,
                        upload_to="docs/national_ids/",
                    ),
                ),
                (
                    "kra_pin",
                    models.FileField(
                        blank=True,
                        help_text="Upload a copy of the your KRA PIN",
                        null=True,
                        upload_to="docs/kra_pins/",
                    ),
                ),
                (
                    "title_deed",
                    models.FileField(
                        blank=True,
                        help_text="Upload a copy of the title deed",
                        null=True,
                        upload_to="docs/title_deeds/",
                    ),
                ),
                (
                    "land_search",
                    models.FileField(
                        blank=True,
                        help_text="Upload the official land search certificate",
                        null=True,
                        upload_to="docs/land_searches/",
                    ),
                ),
                (
                    "lcb_consent",
                    models.FileField(
                        blank=True,
                        help_text="Optional: Upload LCB consent if applicable",
                        null=True,
                        upload_to="docs/lcb_consents/",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SellerProfile",
        ),
        migrations.DeleteModel(
            name="Broker",
        ),
    ]
