# Generated by Django 4.2.29 on 2026-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_link_amenities_to_plot"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="agency_agreement",
            field=models.FileField(
                blank=True,
                help_text="Signed authority letter or agency agreement from the owner.",
                null=True,
                upload_to="documents/agency_agreements/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="agent_commission_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount (KES)")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="agent_commission_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="landowner_phone_for_approval",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_payment_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Per Month"),
                    ("seasonal", "Per Season"),
                    ("yearly", "Per Year"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_term_remaining_years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Years remaining on the leasehold title.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="owner_approval_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="owner_approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="owner_approval_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="owner_approval_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending Landowner Approval"),
                    ("approved", "Approved by Landowner"),
                    ("rejected", "Rejected by Landowner"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="rates_paid_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="rent_paid_up",
            field=models.BooleanField(default=False),
        ),
    ]
