# Generated by Django 4.2.29 on 2026-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_plot_agency_agreement_plot_agent_commission_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="climate_zone",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="plot",
            name="elevation_meters",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_protected_area",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
