# Generated by Django 5.2.10 on 2026-02-12 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_remove_broker_user_profile_is_verified_agent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotimage",
            options={"ordering": ["uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="contactrequest",
            old_name="broker",
            new_name="agent",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="landownerprofile",
            name="title_deed",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="broker",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="seller_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified_agent",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified_broker",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified_landowner",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified_seller",
        ),
        migrations.AddField(
            model_name="agent",
            name="good_conduct",
            field=models.FileField(
                blank=True, null=True, upload_to="docs/good_conduct/"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_number",
            field=models.CharField(default="", help_text="National ID", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="kra_pin",
            field=models.FileField(blank=True, null=True, upload_to="docs/agent_kra/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="practicing_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="docs/practicing_certs/"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="professional_indemnity",
            field=models.FileField(blank=True, null=True, upload_to="docs/indemnity/"),
        ),
        migrations.AddField(
            model_name="plot",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.agent",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="building_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="electricity_meter",
            field=models.BooleanField(default=False, help_text="Has meter installed"),
        ),
        migrations.AddField(
            model_name="plot",
            name="fencing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Full Perimeter"),
                    ("partial", "Partial"),
                    ("none", "No Fencing"),
                    ("live", "Live Fence"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="has_buildings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="has_electricity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="has_road_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="has_water",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="land_type",
            field=models.CharField(
                choices=[
                    ("agricultural", "Agricultural Land"),
                    ("residential", "Residential Plot"),
                    ("commercial", "Commercial Land"),
                    ("mixed_use", "Mixed Use"),
                    ("industrial", "Industrial Land"),
                ],
                default="agricultural",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="land_use_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="landowner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.landownerprofile",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="landowner_id_doc",
            field=models.FileField(
                blank=True,
                help_text="Landowner's national ID",
                null=True,
                upload_to="documents/landowner_ids/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Month-to-Month"),
                    ("seasonal", "Seasonal (3-6 months)"),
                    ("1year", "1 Year"),
                    ("3years", "3 Years"),
                    ("5years", "5 Years"),
                    ("10years", "10 Years"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_price_monthly",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_price_yearly",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("sale", "For Sale"),
                    ("lease", "For Lease"),
                    ("both", "For Sale & Lease"),
                ],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="price_per_acre",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="road_distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tarmac", "Tarmac"),
                    ("murram", "Murram/Gravel"),
                    ("earth", "Earth Road"),
                    ("footpath", "Footpath Only"),
                    ("none", "No Access"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="water_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("borehole", "Borehole"),
                    ("river", "River/Stream"),
                    ("rain", "Rain-fed"),
                    ("irrigation", "Irrigation System"),
                    ("none", "No Water Source"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("landowner", "Landowner"),
                    ("agent", "Agent"),
                    ("admin", "Administrator"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="landownerprofile",
            name="kra_pin",
            field=models.FileField(
                help_text="Upload a copy of your KRA PIN", upload_to="docs/kra_pins/"
            ),
        ),
        migrations.AlterField(
            model_name="landownerprofile",
            name="land_search",
            field=models.FileField(
                blank=True,
                help_text="Upload the official land search certificate (optional)",
                null=True,
                upload_to="docs/land_searches/",
            ),
        ),
        migrations.AlterField(
            model_name="landownerprofile",
            name="national_id",
            field=models.FileField(
                help_text="Upload a copy of your national ID",
                upload_to="docs/national_ids/",
            ),
        ),
        migrations.AlterField(
            model_name="plotimage",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="listings.plot",
            ),
        ),
        migrations.AlterField(
            model_name="soilreport",
            name="ec_salinity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userinterest",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes from agent"),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("title_deed", "Title Deed"),
                    ("official_search", "Official Search Certificate"),
                    ("landowner_id", "Landowner National ID"),
                    ("kra_pin", "KRA PIN Certificate"),
                    ("survey_plan", "Survey Plan"),
                    ("rates_clearance", "Land Rates Clearance"),
                    ("lcb_consent", "LCB Consent"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["-created_at"], name="listings_co_created_1e8679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["responded"], name="listings_co_respond_1ec27a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["-created_at"], name="listings_pl_created_f2d8b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["listing_type"], name="listings_pl_listing_8e4d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["land_type"], name="listings_pl_land_ty_cdb482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["soil_type"], name="listings_pl_soil_ty_67a1b7_idx"
            ),
        ),
    ]
