# Generated by Django 5.2.10 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_add_registry_fields_to_plot"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="lcb_consent_doc",
            field=models.FileField(
                blank=True,
                help_text="Land Control Board consent (agricultural land)",
                null=True,
                upload_to="documents/lcb_consents/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="plupa1_form",
            field=models.FileField(
                blank=True,
                help_text="PLUPA 1 / PPA 1 approval form (subdivision or change of use)",
                null=True,
                upload_to="documents/plupa1_forms/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="consent_to_transfer",
            field=models.FileField(
                blank=True,
                help_text="Consent to transfer for leasehold land",
                null=True,
                upload_to="documents/consent_to_transfer/",
            ),
        ),
    ]
