# Generated by Django 5.2.10 on 2026-02-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("listings", "0017_alter_plotimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("document_uploaded", "Documents Uploaded"),
                            ("api_verification_started", "API Verification Started"),
                            ("title_search_completed", "Title Search Completed"),
                            ("owner_verified", "Owner Identity Verified"),
                            ("encumbrance_check", "Encumbrance Check"),
                            (
                                "physical_location_verified",
                                "Physical Location Verified",
                            ),
                            ("admin_review", "Under Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="document_uploaded",
                        max_length=50,
                    ),
                ),
                ("stage_details", models.JSONField(blank=True, default=dict)),
                ("is_complete", models.BooleanField(default=False)),
                ("api_responses", models.JSONField(blank=True, default=list)),
                ("search_reference", models.CharField(blank=True, max_length=100)),
                (
                    "search_fee_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("document_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("api_started_at", models.DateTimeField(blank=True, null=True)),
                ("title_search_at", models.DateTimeField(blank=True, null=True)),
                ("owner_verified_at", models.DateTimeField(blank=True, null=True)),
                ("admin_review_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted for Verification"),
                            ("document_check", "Document Check"),
                            ("title_search", "Title Search with Ardhisasa"),
                            ("physical_verification", "Physical Verification"),
                            ("admin_approval", "Admin Approval"),
                            ("approved", "Approved for Listing"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("stage_details", models.JSONField(default=dict)),
                ("api_responses", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("title_search_at", models.DateTimeField(blank=True, null=True)),
                ("admin_review_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="listings.plot",
                    ),
                ),
                (
                    "owner_verified",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.verificationstatus",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlotVerificationStatus",
        ),
    ]
