# Generated by Django 5.2.10 on 2026-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0017_add_registry_doc_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("title_deed", "Title Deed"),
                    ("official_search", "Official Search Certificate"),
                    ("landowner_id", "Landowner National ID"),
                    ("kra_pin", "KRA PIN Certificate"),
                    ("survey_map", "Survey Map / Mutation Form"),
                    ("rates_clearance", "Land Rates Clearance"),
                    ("rent_clearance", "Land Rent Clearance"),
                    ("spousal_consent", "Spousal Consent"),
                    ("survey_plan", "Survey Plan"),
                    ("lcb_consent", "LCB Consent"),
                    ("plupa1_form", "PLUPA 1 / PPA 1"),
                    ("consent_to_transfer", "Consent to Transfer"),
                ],
                max_length=30,
            ),
        ),
    ]
