# Generated by Django 5.2.10 on 2026-02-17 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0018_verificationstatus_plotverification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceComparable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("area_acres", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                ("crop_type", models.CharField(blank=True, max_length=200)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for rejection if verification failed (allows re-submission)",
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="landowner_verifications_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="title_deed",
            field=models.FileField(
                blank=True,
                help_text="Land title deed proving ownership (required for verification)",
                null=True,
                upload_to="docs/landowner_title_deeds/",
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="climate_zone",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="plot",
            name="elevation_meters",
            field=models.IntegerField(
                blank=True, help_text="Elevation in metres", null=True
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_protected_area",
            field=models.BooleanField(
                default=False, help_text="Conservancy, forest reserve, etc."
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="special_features",
            field=models.TextField(
                blank=True, help_text="e.g., mature trees, water tank, scenic view"
            ),
        ),
        migrations.AlterField(
            model_name="landownerprofile",
            name="land_search",
            field=models.FileField(
                blank=True,
                help_text="Official land search certificate (ARDHI/Ardhisasa, validity ~3 months)",
                null=True,
                upload_to="docs/land_searches/",
            ),
        ),
        migrations.CreateModel(
            name="PricingSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_range_min",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_range_max",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("methodology", models.CharField(blank=True, max_length=200)),
                ("comparable_plots_used", models.IntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("landowner_accepted", models.BooleanField(blank=True, null=True)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_suggestions",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_type", models.CharField(max_length=50)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="listings.plot",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("document_review", "Document Review"),
                            ("extension_review", "Extension Officer Review"),
                            ("surveyor_inspection", "Land Surveyor Inspection"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("approved", models.BooleanField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_verification_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tasks",
                        to="listings.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_plot", "Create Listing"),
                            ("edit_plot", "Edit Listing"),
                            ("delete_plot", "Delete Listing"),
                            ("verify_landowner", "Verify Landowner"),
                            ("reject_landowner", "Reject Landowner"),
                            ("verify_agent", "Verify Agent"),
                            ("verify_plot", "Verify Plot"),
                            ("reject_plot", "Reject Plot"),
                            ("change_price", "Change Price"),
                            ("login", "Login"),
                            ("failed_login", "Failed Login"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="listings_au_created_586adf_idx"
                    ),
                    models.Index(
                        fields=["user", "action"], name="listings_au_user_id_f2005d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("kra_pin", "KRA PIN"),
                            ("title_deed", "Title Deed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                ("is_readable", models.BooleanField(blank=True, null=True)),
                ("is_not_expired", models.BooleanField(blank=True, null=True)),
                ("name_matches_user", models.BooleanField(blank=True, null=True)),
                ("all_names_match", models.BooleanField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("approved", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "document_type")},
            },
        ),
    ]
