# Generated by Django 5.2.10 on 2026-02-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0020_plot_latitude_longitude_remove_plotimage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plot",
            new_name="listings_pl_latitud_549932_idx",
            old_name="listings_pl_latitud_7c2e0d_idx",
        ),
    ]
