# Generated by Django 5.2.10 on 2026-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0021_rename_listings_pl_latitud_7c2e0d_idx_listings_pl_latitud_549932_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="subcounty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
