# Generated by Django 5.2.10 on 2026-02-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0023_emaillog_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Government/Institution employee ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g., Agricultural Officer, Livestock Officer",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(default="Ministry of Agriculture", max_length=100),
                ),
                (
                    "station",
                    models.CharField(
                        help_text="Assigned location/office", max_length=200
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Academic and professional qualifications"
                    ),
                ),
                (
                    "specializations",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Crop Science, Soil Science",
                        max_length=300,
                    ),
                ),
                ("years_of_experience", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20)),
                ("office_address", models.TextField(blank=True)),
                (
                    "assigned_counties",
                    models.JSONField(
                        default=list, help_text="List of counties they can verify"
                    ),
                ),
                (
                    "max_daily_tasks",
                    models.IntegerField(default=5, help_text="Maximum tasks per day"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "response_time_avg",
                    models.FloatField(
                        default=0, help_text="Average response time in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_officers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtensionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("weather_conditions", models.CharField(blank=True, max_length=100)),
                ("soil_ph_verified", models.FloatField(blank=True, null=True)),
                (
                    "soil_texture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "soil_depth",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Deep (>50cm), Medium (25-50cm), Shallow (<25cm)",
                        max_length=50,
                    ),
                ),
                (
                    "soil_drainage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("moderate", "Moderate"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "existing_crops",
                    models.TextField(blank=True, help_text="Crops currently growing"),
                ),
                (
                    "crop_health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pest_issues", models.TextField(blank=True)),
                ("disease_issues", models.TextField(blank=True)),
                ("water_source_verified", models.CharField(blank=True, max_length=100)),
                (
                    "water_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("irrigation_system", models.CharField(blank=True, max_length=100)),
                (
                    "site_photos",
                    models.JSONField(default=list, help_text="List of photo URLs"),
                ),
                ("recommended_crops", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
                (
                    "overall_suitability",
                    models.CharField(
                        choices=[
                            ("highly_suitable", "Highly Suitable"),
                            ("moderately_suitable", "Moderately Suitable"),
                            ("marginally_suitable", "Marginally Suitable"),
                            ("not_suitable", "Not Suitable"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_conditions", "Approve with Conditions"),
                            ("reject", "Reject"),
                            ("further_review", "Further Review Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comments", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="listings.extensionofficer",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_reports",
                        to="listings.plot",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_report",
                        to="listings.verificationtask",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="extensionofficer",
            index=models.Index(
                fields=["station"], name="listings_ex_station_8f7800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionofficer",
            index=models.Index(
                fields=["is_active"], name="listings_ex_is_acti_6c1c67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionreport",
            index=models.Index(
                fields=["visit_date"], name="listings_ex_visit_d_2aa2cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionreport",
            index=models.Index(
                fields=["officer", "-submitted_at"],
                name="listings_ex_officer_74adc6_idx",
            ),
        ),
    ]
