# Generated by Django 5.2.10 on 2026-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0024_extensionofficer_extensionreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
