# Generated by Django 5.2.10 on 2026-02-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0025_plot_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_requests",
                to="listings.agent",
            ),
        ),
    ]
