# Generated by Django 5.2.10 on 2026-02-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0026_alter_contactrequest_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
