# Generated by Django 5.2.10 on 2026-02-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("listings", "0028_profile_email_verified_profile_has_2fa_enabled_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="verificationstatus",
            unique_together={("content_type", "object_id")},
        ),
    ]
