# Generated by Django 5.2.10 on 2026-02-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0029_alter_verificationstatus_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandSurveyor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g., Licensed Land Surveyor", max_length=100
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        help_text="Assigned location/office", max_length=200
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Academic and professional qualifications"
                    ),
                ),
                ("years_of_experience", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20)),
                ("office_address", models.TextField(blank=True)),
                (
                    "assigned_counties",
                    models.JSONField(
                        default=list, help_text="List of counties they can verify"
                    ),
                ),
                (
                    "max_daily_tasks",
                    models.IntegerField(default=5, help_text="Maximum tasks per day"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                (
                    "response_time_avg",
                    models.FloatField(
                        default=0, help_text="Average response time in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_surveyor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_surveyors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("boundary_confirmed", models.BooleanField(default=False)),
                ("acreage_confirmed", models.BooleanField(default=False)),
                ("encumbrances_found", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_conditions", "Approve with Conditions"),
                            ("reject", "Reject"),
                            ("further_review", "Further Review Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveyor_reports",
                        to="listings.plot",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="listings.landsurveyor",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveyor_report",
                        to="listings.verificationtask",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="landsurveyor",
            index=models.Index(
                fields=["station"], name="listings_la_station_7e09fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landsurveyor",
            index=models.Index(
                fields=["is_active"], name="listings_la_is_acti_92866f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyorreport",
            index=models.Index(
                fields=["visit_date"], name="listings_su_visit_d_0f0638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyorreport",
            index=models.Index(
                fields=["surveyor", "-submitted_at"],
                name="listings_su_surveyo_ddf4c2_idx",
            ),
        ),
    ]
