# Generated by Django 5.2.10 on 2026-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0031_emailotp"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP INDEX IF EXISTS listings_em_email_0e1f1a_idx;",
                "CREATE INDEX IF NOT EXISTS listings_em_email_c7b849_idx ON listings_emailotp (email, otp, expires_at);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS listings_em_email_c7b849_idx;",
                "CREATE INDEX IF NOT EXISTS listings_em_email_0e1f1a_idx ON listings_emailotp (email, otp, expires_at);",
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="emailotp",
                    name="listings_em_email_0e1f1a_idx",
                ),
                migrations.AddIndex(
                    model_name="emailotp",
                    index=models.Index(
                        fields=["email", "otp", "expires_at"],
                        name="listings_em_email_c7b849_idx",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
