# Generated by Django 5.2.10 on 2026-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0032_rename_listings_em_email_0e1f1a_idx_listings_em_email_c7b849_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyorreport",
            name="access_road",
            field=models.CharField(
                blank=True,
                help_text="Describe road access and distance to main road",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="boundary_markers",
            field=models.TextField(
                blank=True,
                help_text="Describe boundary markers or beacons found on site",
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="encumbrance_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="mutation_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="subdivision_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="topography_notes",
            field=models.TextField(
                blank=True, help_text="Slope, terrain, drainage patterns, or obstacles"
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="utilities_available",
            field=models.TextField(
                blank=True, help_text="Water, electricity, irrigation, other utilities"
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="crop_suitability",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="plot",
            name="soil_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
