# Generated by Django 5.2.10 on 2026-02-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0033_surveyorreport_access_road_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="is_price_negotiable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="lease_basis",
            field=models.CharField(
                choices=[
                    ("owner_set", "Owner-set price"),
                    ("agent_market", "Agent market analysis"),
                    ("valuation_report", "Professional valuation report"),
                    ("government_set", "Government-set price"),
                    ("negotiated", "Negotiated (market demand)"),
                ],
                default="owner_set",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="price_basis",
            field=models.CharField(
                choices=[
                    ("owner_set", "Owner-set price"),
                    ("agent_market", "Agent market analysis"),
                    ("valuation_report", "Professional valuation report"),
                    ("government_set", "Government-set price"),
                    ("negotiated", "Negotiated (market demand)"),
                ],
                default="owner_set",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="price_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes on how price was determined (market trends, valuation, negotiations)",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="valuation_report",
            field=models.FileField(
                blank=True,
                help_text="Optional valuation report (PDF/Image)",
                null=True,
                upload_to="documents/valuation_reports/",
            ),
        ),
    ]
