# Generated by Django 5.2.10 on 2026-02-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0034_plot_is_price_negotiable_plot_lease_basis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="encumbrance_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="encumbrances",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="government_price_proof",
            field=models.FileField(
                blank=True,
                help_text="Official notice/gazette for government-set price",
                null=True,
                upload_to="documents/government_price_proofs/",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="nearest_town",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="plot",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("freehold", "Freehold"),
                    ("leasehold", "Leasehold"),
                    ("government", "Government"),
                    ("community", "Community"),
                ],
                default="freehold",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="tenure_details",
            field=models.CharField(
                blank=True,
                help_text="Lease duration/expiry or tenure notes",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="ComparableSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Market source or reference",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparables",
                        to="listings.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketPriceBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural Land"),
                            ("residential", "Residential Plot"),
                            ("commercial", "Commercial Land"),
                            ("mixed_use", "Mixed Use"),
                            ("industrial", "Industrial Land"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("lease", "For Lease"),
                            ("both", "For Sale & Lease"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_price_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["county", "land_type", "listing_type"],
                        name="listings_ma_county_9348d1_idx",
                    )
                ],
            },
        ),
    ]
