# Generated by Django 5.2.10 on 2026-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0035_plot_encumbrance_details_plot_encumbrances_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyorreport",
            name="price_realistic",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="price_review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="suggested_price_per_acre",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="surveyorreport",
            name="suggested_sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
