# Generated by Django 5.2.10 on 2026-02-26 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0036_surveyorreport_price_realistic_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentverification",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentverification",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_verifications",
                to="listings.plot",
            ),
        ),
        migrations.AddField(
            model_name="documentverification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_verifications",
                to="listings.verificationtask",
            ),
        ),
        migrations.AlterField(
            model_name="documentverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("kra_pin", "KRA PIN"),
                    ("title_deed", "Title Deed"),
                    ("official_search", "Official Search"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentverification",
            unique_together={("user", "document_type", "plot")},
        ),
    ]
