# Generated by Django 5.2.10 on 2026-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0037_alter_documentverification_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationtask",
            name="confirm_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationtask",
            name="confirmation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="verificationtask",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationtask",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
