# Generated by Django 5.2.10 on 2026-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0038_verificationtask_confirm_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtask",
            name="confirmation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
