# Generated by Django 5.2.10 on 2026-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0040_merge_0039_alter_verificationtask_confirmation_status_0039_supportticket_smslog",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("task_reminder", "Task Reminder"),
                    ("task_unconfirmed", "Task Unconfirmed"),
                    ("plot_submitted", "Plot Submitted"),
                    ("plot_approved", "Plot Approved"),
                    ("plot_rejected", "Plot Rejected"),
                    ("plot_stage_update", "Plot Stage Update"),
                    ("changes_requested", "Changes Requested"),
                    ("document_uploaded", "Document Uploaded"),
                    ("verification_started", "Verification Started"),
                    ("verification_completed", "Verification Completed"),
                    ("verification_step_update", "Verification Step Update"),
                    ("no_officer_available", "No Officer Available"),
                    ("role_request", "Role Request"),
                    ("role_approved", "Role Approved"),
                    ("account_verified", "Account Verified"),
                ],
                max_length=50,
            ),
        ),
    ]
