# Generated by Django 5.2.10 on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0041_alter_notification_notification_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlotReaction",
        ),
    ]
