# Generated by Django 5.2.10 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0042_remove_plotreaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(choices=[("about", "About Us"), ("terms", "Terms of Service"), ("privacy", "Privacy Policy")], max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
    ]
