# Generated by Django 5.2.10 on 2026-03-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="",
                        help_text="Kindly provide your Phone Number",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Professional license number",
                        max_length=100,
                    ),
                ),
                (
                    "license_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_licenses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("id_number", models.CharField(help_text="National ID", max_length=20)),
                (
                    "kra_pin",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_kra/"
                    ),
                ),
                (
                    "practicing_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/practicing_certs/"
                    ),
                ),
                (
                    "good_conduct",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/good_conduct/"
                    ),
                ),
                (
                    "professional_indemnity",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/indemnity/"
                    ),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=100.0, help_text="Percentage of inquiries responded to"
                    ),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=24, help_text="Average response time in hours"
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("review_count", models.IntegerField(default=0)),
                ("total_listings", models.IntegerField(default=0)),
                ("verified_listings", models.IntegerField(default=0)),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("available_from", models.TimeField(default="09:00")),
                ("available_to", models.TimeField(default="17:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_agent",
            },
        ),
        migrations.CreateModel(
            name="LandownerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id",
                    models.FileField(
                        help_text="Upload a copy of your national ID",
                        upload_to="docs/national_ids/",
                    ),
                ),
                (
                    "kra_pin",
                    models.FileField(
                        help_text="Upload a copy of your KRA PIN",
                        upload_to="docs/kra_pins/",
                    ),
                ),
                (
                    "title_deed",
                    models.FileField(
                        blank=True,
                        help_text="Land title deed proving ownership (required for verification)",
                        null=True,
                        upload_to="docs/landowner_title_deeds/",
                    ),
                ),
                (
                    "land_search",
                    models.FileField(
                        blank=True,
                        help_text="Official land search certificate (ARDHI/Ardhisasa, validity ~3 months)",
                        null=True,
                        upload_to="docs/land_searches/",
                    ),
                ),
                (
                    "lcb_consent",
                    models.FileField(
                        blank=True,
                        help_text="Optional: Upload LCB consent if applicable",
                        null=True,
                        upload_to="docs/lcb_consents/",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if verification failed (allows re-submission)",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landowner_verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_landownerprofile",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("has_2fa_enabled", models.BooleanField(default=False)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("landowner", "Landowner"),
                            ("agent", "Agent"),
                            ("admin", "Administrator"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_profile",
            },
        ),
    ]
