# Generated by Django 4.2.29 on 2026-06-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("has_2fa_enabled", models.BooleanField(default=False)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("buy", "Buying Land"),
                            ("lease_in", "Leasing/Renting In"),
                            ("sell", "Selling Land"),
                            ("lease_out", "Leasing/Renting Out"),
                            ("professional", "Providing Services (Agent/Surveyor)"),
                        ],
                        default="buy",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("landowner", "Landowner"),
                            ("agent", "Agent"),
                            ("advocate", "Advocate"),
                            ("lawyer", "Lawyer"),
                            ("admin", "Administrator"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_profile",
            },
        ),
        migrations.CreateModel(
            name="LandownerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Full legal name as it appears on the title deed and ID.",
                        max_length=200,
                    ),
                ),
                (
                    "national_id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID or passport number.",
                        max_length=20,
                    ),
                ),
                (
                    "kra_pin_number",
                    models.CharField(
                        blank=True,
                        help_text="KRA PIN number used for CGT and identity checks.",
                        max_length=20,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("single", "Single"), ("married", "Married")],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("spouse_full_name", models.CharField(blank=True, max_length=200)),
                ("spouse_id_number", models.CharField(blank=True, max_length=20)),
                (
                    "spouse_id_doc",
                    models.FileField(
                        blank=True,
                        help_text="Spouse ID copy when the land is matrimonial property.",
                        null=True,
                        upload_to="docs/spousal_ids/",
                    ),
                ),
                ("land_rates_paid_up", models.BooleanField(default=False)),
                ("land_rent_paid_up", models.BooleanField(default=False)),
                (
                    "national_id",
                    models.FileField(
                        help_text="Upload a copy of your national ID",
                        upload_to="docs/national_ids/",
                    ),
                ),
                (
                    "kra_pin",
                    models.FileField(
                        help_text="Upload a copy of your KRA PIN",
                        upload_to="docs/kra_pins/",
                    ),
                ),
                (
                    "title_deed",
                    models.FileField(
                        blank=True,
                        help_text="Land title deed proving ownership (required for verification)",
                        null=True,
                        upload_to="docs/landowner_title_deeds/",
                    ),
                ),
                (
                    "land_search",
                    models.FileField(
                        blank=True,
                        help_text="Official land search certificate (ARDHI/Ardhisasa, validity ~3 months)",
                        null=True,
                        upload_to="docs/land_searches/",
                    ),
                ),
                (
                    "lcb_consent",
                    models.FileField(
                        blank=True,
                        help_text="Optional: Upload LCB consent if applicable",
                        null=True,
                        upload_to="docs/lcb_consents/",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if verification failed (allows re-submission)",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landowner_verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_landownerprofile",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="",
                        help_text="Kindly provide your Phone Number",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Professional license number",
                        max_length=100,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Registered company or agency name, if applicable.",
                        max_length=200,
                    ),
                ),
                (
                    "earb_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Estate Agents Registration Board (EARB) number.",
                        max_length=100,
                    ),
                ),
                (
                    "license_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_licenses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("id_number", models.CharField(help_text="National ID", max_length=20)),
                (
                    "kra_pin",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_kra/"
                    ),
                ),
                (
                    "tax_compliance_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/agent_tax_compliance/"
                    ),
                ),
                (
                    "practicing_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/practicing_certs/"
                    ),
                ),
                (
                    "good_conduct",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/good_conduct/"
                    ),
                ),
                (
                    "professional_indemnity",
                    models.FileField(
                        blank=True, null=True, upload_to="docs/indemnity/"
                    ),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=100.0, help_text="Percentage of inquiries responded to"
                    ),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=24, help_text="Average response time in hours"
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("review_count", models.IntegerField(default=0)),
                ("total_listings", models.IntegerField(default=0)),
                ("verified_listings", models.IntegerField(default=0)),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("available_from", models.TimeField(default="09:00")),
                ("available_to", models.TimeField(default="17:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings_agent",
            },
        ),
    ]
