# Generated by Django 4.2.29 on 2026-06-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="intent",
            field=models.CharField(
                choices=[
                    ("buy", "Buying Land"),
                    ("lease_in", "Leasing or Renting Land In"),
                    ("sell", "Selling Land"),
                    ("lease_out", "Leasing or Renting Land Out"),
                    ("professional", "Providing Land Services"),
                ],
                default="buy",
                max_length=20,
            ),
        ),
    ]
