# Generated by Django 5.2.10 on 2026-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="intent",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("tenant", "Tenant"),
                    ("buyer", "Buyer"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("landowner", "Landowner"),
                    ("agent", "Agent"),
                    ("advocate", "Advocate"),
                    ("lawyer", "Lawyer"),
                    ("admin", "Administrator"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
    ]
