# Generated by Django 4.2.29 on 2026-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_address_profile_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Registered company or agency name, if applicable.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="earb_registration_number",
            field=models.CharField(
                blank=True,
                help_text="Estate Agents Registration Board (EARB) number.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="tax_compliance_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="docs/agent_tax_compliance/"
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="kra_pin_number",
            field=models.CharField(
                blank=True,
                help_text="KRA PIN number used for CGT and identity checks.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="land_rates_paid_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="land_rent_paid_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Full legal name as it appears on the title deed and ID.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="marital_status",
            field=models.CharField(
                choices=[("single", "Single"), ("married", "Married")],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="national_id_number",
            field=models.CharField(
                blank=True, help_text="National ID or passport number.", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="spouse_full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="spouse_id_doc",
            field=models.FileField(
                blank=True,
                help_text="Spouse ID copy when the land is matrimonial property.",
                null=True,
                upload_to="docs/spousal_ids/",
            ),
        ),
        migrations.AddField(
            model_name="landownerprofile",
            name="spouse_id_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
