# Generated by Django 4.2.29 on 2026-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_agent_company_name_agent_earb_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
