# Generated by Django 4.2.29 on 2026-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="intent",
            field=models.CharField(
                choices=[
                    ("buy", "Buying Land"),
                    ("lease_in", "Leasing/Renting In"),
                    ("sell", "Selling Land"),
                    ("lease_out", "Leasing/Renting Out"),
                    ("professional", "Providing Services (Agent/Surveyor)"),
                ],
                default="buy",
                max_length=20,
            ),
        ),
    ]
