# Generated by Django 4.2.29 on 2026-06-13 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("lease", "Lease"),
                            ("both", "Purchase & Lease"),
                        ],
                        default="purchase",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            (
                                "due_diligence",
                                "Due Diligence (Official Search & Survey)",
                            ),
                            ("commitment", "Letter of Offer (Intent to Purchase)"),
                            (
                                "contracts",
                                "Sale Agreement & 10% Escrow Deposit (Platform Holds)",
                            ),
                            ("statutory_consents", "LCB Consent & Spousal Consent"),
                            ("taxation", "Stamp Duty (Paid Directly to KRA via iTax)"),
                            ("registration", "Title Registration & Transfer"),
                            ("disbursement", "Platform Fee Deduction & Seller Payout"),
                            ("completed", "Completed & Reports Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("agreed_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "ten_percent_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ninety_percent_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="10% deposit held in platform escrow",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="90% balance held in platform escrow",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Platform fee percentage (1.5-3%)",
                        max_digits=5,
                    ),
                ),
                (
                    "platform_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform fee deducted from seller proceeds",
                        max_digits=15,
                    ),
                ),
                (
                    "seller_net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Seller receives after platform fee deduction",
                        max_digits=15,
                    ),
                ),
                (
                    "stamp_duty_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="2% rural, 4% urban",
                        max_digits=5,
                    ),
                ),
                (
                    "stamp_duty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Paid directly to KRA, not collected by platform",
                        max_digits=15,
                    ),
                ),
                (
                    "capital_gains_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="15% of profit - Seller files with KRA",
                        max_digits=15,
                    ),
                ),
                (
                    "deposit_held_in_escrow_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When 10% deposit was received in escrow",
                        null=True,
                    ),
                ),
                (
                    "balance_held_in_escrow_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When 90% balance was received in escrow",
                        null=True,
                    ),
                ),
                (
                    "disbursed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When funds were released to seller after registration",
                        null=True,
                    ),
                ),
                (
                    "platform_fee_deducted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When platform fee was deducted",
                        null=True,
                    ),
                ),
                (
                    "stamp_duty_receipt_uploaded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "stamp_duty_receipt_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "stamp_duty_receipt_number",
                    models.CharField(
                        blank=True, help_text="KRA iTax receipt number", max_length=100
                    ),
                ),
                (
                    "due_diligence_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "commitment_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("contracts_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "statutory_consents_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("taxation_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "disbursement_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("lcb_meeting_date", models.DateField(blank=True, null=True)),
                ("lcb_consent_reference", models.CharField(blank=True, max_length=100)),
                (
                    "lcb_application_fee",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reports_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When transaction reports were emailed to both parties",
                        null=True,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer_advocate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Licensed advocate representing the buyer (required by Law Society of Kenya)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyer_representations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_request",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated payment request for this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_transactions",
                        to="listings.plot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_advocate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Licensed advocate representing the seller (required by Law Society of Kenya)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_representations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stamp_duty_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_stamp_duty_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            (
                                "due_diligence",
                                "Due Diligence Completed (Land Act 2012)",
                            ),
                            ("commitment", "Letter of Offer Issued"),
                            (
                                "contracts",
                                "Sale Agreement Signed & 10% Escrow (LSK Conditions)",
                            ),
                            ("statutory_consents", "LCB & Spousal Consents Obtained"),
                            ("taxation", "Stamp Duty Paid to KRA (Tax Laws)"),
                            ("registration", "Title Transferred (LRA 2012)"),
                            (
                                "disbursement",
                                "Funds Disbursed to Seller (Platform Fee Deducted)",
                            ),
                            ("completed", "Transaction Completed & Reports Sent"),
                            ("cancelled", "Transaction Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "achieved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["achieved_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "OFFICIAL_SEARCH",
                                "Official Land Search Certificate (From ArdhiSasa Portal)",
                            ),
                            ("SURVEY_MAP", "Survey Map / Beacon Report / RIM"),
                            ("LETTER_OF_OFFER", "Letter of Offer (Intent to Purchase)"),
                            ("SALE_AGREEMENT", "Signed Sale Agreement (LSK Form)"),
                            ("LCB_CONSENT", "Land Control Board Consent (Cap 302)"),
                            (
                                "SPOUSAL_CONSENT",
                                "Spousal Consent Affidavit (LRA 2012, Sec 93)",
                            ),
                            (
                                "STAMP_DUTY_RECEIPT",
                                "Stamp Duty Payment Receipt (KRA iTax)",
                            ),
                            ("VALUATION_REPORT", "Government Valuation Report"),
                            ("TRANSFER_FORM", "Signed Transfer Form (RL 1)"),
                            (
                                "ORIGINAL_TITLE_DEED",
                                "Original Title Deed (Surrendered)",
                            ),
                            (
                                "NEW_TITLE_DEED",
                                "New Certificate of Title (Buyer's Name)",
                            ),
                            ("ID_DOCUMENT", "National ID (Buyer/Seller)"),
                            ("KRA_PIN", "KRA PIN Certificate"),
                            (
                                "RATES_CLEARANCE",
                                "Land Rates Clearance Certificate (County)",
                            ),
                            (
                                "RENT_CLEARANCE",
                                "Land Rent Clearance Certificate (National)",
                            ),
                            ("PASSPORT_PHOTO", "Passport Photos (Buyer/Seller)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="transactions/documents/%Y/%m/%d/"),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "document_date",
                    models.DateField(
                        blank=True, help_text="Date on the document", null=True
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="LCB ref, Stamp Duty ref, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "search_date",
                    models.DateField(
                        blank=True,
                        help_text="For official search certificates",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified by Admin"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("transaction", "document_type")},
            },
        ),
    ]
