# Generated by Django 4.2.29 on 2026-06-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreed_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Negotiation"),
                            ("due_diligence", "Due Diligence (Search & Site Visit)"),
                            ("sale_agreement", "Sale Agreement Execution"),
                            ("lcb_consent", "Land Control Board Consent"),
                            ("valuation", "Government Valuation"),
                            ("stamp_duty", "Stamp Duty Payment"),
                            ("transfer_execution", "Transfer Execution (Form 30)"),
                            ("registration", "Registry Registration"),
                            ("completed", "Completed / Handover"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company / Corporate"),
                            ("trust", "Trust"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "buyer_id_number",
                    models.CharField(
                        blank=True, help_text="National ID or Reg Number", max_length=50
                    ),
                ),
                ("buyer_kra_pin", models.CharField(blank=True, max_length=20)),
                ("buyer_address", models.TextField(blank=True)),
                ("seller_advocate", models.CharField(blank=True, max_length=200)),
                ("buyer_advocate", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_transactions",
                        to="listings.plot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Negotiation"),
                            ("due_diligence", "Due Diligence (Search & Site Visit)"),
                            ("sale_agreement", "Sale Agreement Execution"),
                            ("lcb_consent", "Land Control Board Consent"),
                            ("valuation", "Government Valuation"),
                            ("stamp_duty", "Stamp Duty Payment"),
                            ("transfer_execution", "Transfer Execution (Form 30)"),
                            ("registration", "Registry Registration"),
                            ("completed", "Completed / Handover"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("sale_agreement", "Signed Sale Agreement"),
                            ("transfer_form", "Transfer Form (Form 30)"),
                            ("stamp_duty_receipt", "Stamp Duty Receipt"),
                            ("valuation_report", "Government Valuation Report"),
                            ("lcb_consent", "LCB Consent Certificate"),
                            ("cr12", "CR12 (for Companies)"),
                            ("buyer_id", "Buyer National ID"),
                            ("buyer_photo", "Buyer Passport Photo"),
                            (
                                "registration_proof",
                                "Registration Proof / New Title Copy",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="transaction_docs/")),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
    ]
