# Generated by Django 4.2.29 on 2026-06-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated this transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="stage",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("due_diligence", "Due Diligence"),
                    ("commitment", "Offer Agreement (Negotiation & Drafting)"),
                    ("contracts", "Agreement Deposit (10% Escrow Payment)"),
                    ("statutory_consents", "Statutory Consents"),
                    ("taxation", "Stamp Duty Payment (Direct to KRA)"),
                    ("completion", "Completion Balance (Final Payment)"),
                    ("registration", "Final Registration & Title Issuance"),
                    ("disbursement", "Disbursement & Completion"),
                    ("completed", "Workflow Complete"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transactionmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("due_diligence", "Due Diligence Completed (Land Act 2012)"),
                    ("commitment", "Letter of Offer Issued"),
                    (
                        "contracts",
                        "Sale Agreement Signed & 10% Escrow (LSK Conditions)",
                    ),
                    ("statutory_consents", "LCB & Spousal Consents Obtained"),
                    ("taxation", "Stamp Duty Paid to KRA (Tax Laws)"),
                    ("completion", "Completion Balance Paid"),
                    ("registration", "Title Transferred (LRA 2012)"),
                    (
                        "disbursement",
                        "Funds Disbursed to Seller (Platform Fee Deducted)",
                    ),
                    ("completed", "Transaction Completed & Reports Sent"),
                    ("cancelled", "Transaction Cancelled"),
                ],
                max_length=30,
            ),
        ),
    ]
