# Generated by Django 4.2.29 on 2026-06-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
        ("payments", "0004_walletdepositrequest_payment_request_and_more"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactiondocument",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="transactionmilestone",
            options={"ordering": ["achieved_at"]},
        ),
        migrations.RenameField(
            model_name="transactionmilestone",
            old_name="created_at",
            new_name="achieved_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyer_address",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyer_advocate",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyer_id_number",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyer_kra_pin",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyer_type",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="seller_advocate",
        ),
        migrations.RemoveField(
            model_name="transactionmilestone",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="transactionmilestone",
            name="stage",
        ),
        migrations.AddField(
            model_name="transaction",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="capital_gains_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="commitment_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="contracts_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_diligence_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="escrow_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.escrowaccount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="lcb_application_fee",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="lcb_consent_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="lcb_meeting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ninety_percent_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="registration_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stamp_duty_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stamp_duty_percentage",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="transaction",
            name="statutory_consents_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="taxation_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ten_percent_deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("lease", "Lease"),
                    ("both", "Purchase & Lease"),
                ],
                default="purchase",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="document_date",
            field=models.DateField(
                blank=True, help_text="Date on the document", null=True
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("OFFICIAL_SEARCH", "Official Land Search Certificate (ArdhiSasa)"),
                    ("SURVEY_MAP", "Survey Map / Beacon Report / RIM"),
                    ("LETTER_OF_OFFER", "Letter of Offer (Intent to Purchase)"),
                    ("SALE_AGREEMENT", "Signed Sale Agreement (LSK Form)"),
                    ("LCB_CONSENT", "Land Control Board Consent (Cap 302)"),
                    ("SPOUSAL_CONSENT", "Spousal Consent Affidavit (LRA 2012, Sec 93)"),
                    ("STAMP_DUTY_RECEIPT", "Stamp Duty Payment Receipt (eCitizen)"),
                    ("VALUATION_REPORT", "Government Valuation Report"),
                    ("CGT_RECEIPT", "Capital Gains Tax Payment Receipt (15%)"),
                    ("TRANSFER_FORM", "Signed Transfer Form (RL 1)"),
                    ("NEW_TITLE_DEED", "New Certificate of Title (Buyer's Name)"),
                    ("ID_DOCUMENT", "National ID (Buyer/Seller)"),
                    ("KRA_PIN", "KRA PIN Certificate"),
                    ("RATES_CLEARANCE", "Land Rates Clearance Certificate (County)"),
                    ("RENT_CLEARANCE", "Land Rent Clearance Certificate (National)"),
                    ("PASSPORT_PHOTO", "Passport Photos (Buyer/Seller)"),
                ],
                default="SALE_AGREEMENT",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, help_text="File size in bytes"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="filename",
            field=models.CharField(default="document.pdf", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="mime_type",
            field=models.CharField(default="application/pdf", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="reference_number",
            field=models.CharField(
                blank=True, help_text="LCB ref, Stamp Duty ref, etc.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="search_date",
            field=models.DateField(
                blank=True, help_text="For official search certificates", null=True
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified by Admin"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="uploaded_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionmilestone",
            name="achieved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("due_diligence", "Due Diligence Completed (Land Act 2012)"),
                    ("commitment", "Letter of Offer Issued"),
                    (
                        "contracts",
                        "Sale Agreement Signed & 10% Escrow (LSK Conditions)",
                    ),
                    ("statutory_consents", "LCB & Spousal Consents Obtained"),
                    ("taxation", "Stamp Duty & CGT Paid (Tax Laws)"),
                    ("registration", "Title Transferred (LRA 2012)"),
                    ("completed", "Transaction Completed & Disbursed"),
                    ("cancelled", "Transaction Cancelled"),
                ],
                default="due_diligence",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="agreed_price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deposit_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_transactions",
                to="listings.plot",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="land_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="stage",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("due_diligence", "Due Diligence (Official Search & Survey)"),
                    ("commitment", "Letter of Offer (Intent to Purchase)"),
                    ("contracts", "Sale Agreement & 10% Escrow Deposit"),
                    ("statutory_consents", "LCB Consent & Spousal Consent"),
                    ("taxation", "Stamp Duty & Capital Gains Tax"),
                    ("registration", "Title Registration & Transfer"),
                    ("completed", "Completed & Disbursed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="file",
            field=models.FileField(upload_to="transactions/documents/%Y/%m/%d/"),
        ),
        migrations.AlterUniqueTogether(
            name="transactiondocument",
            unique_together={("transaction", "document_type")},
        ),
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="transactiondocument",
            name="doc_type",
        ),
        migrations.RemoveField(
            model_name="transactiondocument",
            name="is_verified",
        ),
    ]
