# Generated by Django 4.2.29 on 2026-06-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_walletdepositrequest_payment_request_and_more"),
        ("transactions", "0002_alter_transactiondocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_transaction",
                to="payments.paymentrequest",
            ),
        ),
    ]
