# Generated by Django 4.2.29 on 2026-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_payment_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="escrow_account",
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    (
                        "OFFICIAL_SEARCH",
                        "Official Land Search Certificate (From ArdhiSasa Portal)",
                    ),
                    ("SURVEY_MAP", "Survey Map / Beacon Report / RIM"),
                    ("LETTER_OF_OFFER", "Letter of Offer (Intent to Purchase)"),
                    ("SALE_AGREEMENT", "Signed Sale Agreement (LSK Form)"),
                    ("LCB_CONSENT", "Land Control Board Consent (Cap 302)"),
                    ("SPOUSAL_CONSENT", "Spousal Consent Affidavit (LRA 2012, Sec 93)"),
                    ("STAMP_DUTY_ASSESSMENT", "Stamp Duty Assessment Form"),
                    ("STAMP_DUTY_RECEIPT", "Stamp Duty Payment Receipt (eCitizen)"),
                    ("VALUATION_REPORT", "Government Valuation Report"),
                    ("CGT_RECEIPT", "Capital Gains Tax Payment Receipt (15%)"),
                    ("TRANSFER_FORM", "Signed Transfer Form (RL 1)"),
                    ("ORIGINAL_TITLE_DEED", "Original Title Deed (Surrendered)"),
                    ("NEW_TITLE_DEED", "New Certificate of Title (Buyer's Name)"),
                    ("ID_DOCUMENT", "National ID (Buyer/Seller)"),
                    ("KRA_PIN", "KRA PIN Certificate"),
                    ("RATES_CLEARANCE", "Land Rates Clearance Certificate (County)"),
                    ("RENT_CLEARANCE", "Land Rent Clearance Certificate (National)"),
                    ("PASSPORT_PHOTO", "Passport Photos (Buyer/Seller)"),
                ],
                max_length=30,
            ),
        ),
    ]
