# Generated by Django 4.2.29 on 2026-06-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "totp_secret",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Setting",
                "verbose_name_plural": "2FA Settings",
                "db_table": "security_twofactorsettings",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorBackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Backup Code",
                "verbose_name_plural": "2FA Backup Codes",
                "db_table": "security_twofactorbackupcode",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhoneEmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "phone_verification_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "email_verification_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Verification",
                "verbose_name_plural": "Contact Verifications",
                "db_table": "security_phoneemailverification",
            },
        ),
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("otp", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("verification", "Verification"),
                            ("password_reset", "Password Reset"),
                            ("transaction", "Transaction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_phoneotp",
                "indexes": [
                    models.Index(
                        fields=["phone", "otp", "expires_at"],
                        name="security_ph_phone_9f3e22_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="security_ph_expires_0f154a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImpersonationDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("duplicate_id", "Same ID multiple accounts"),
                            ("name_mismatch", "Name mismatch across documents"),
                            ("rapid_listings", "Too many listings too quickly"),
                            ("geographic_mismatch", "Listings far apart"),
                            ("content_similarity", "Listing description copied"),
                            ("suspicious_login", "Suspicious login pattern"),
                            ("multiple_accounts", "Multiple accounts with same ID"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk - Block"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_impersonationdetection",
                "ordering": ["-severity", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="security_im_severit_39c0ac_idx",
                    ),
                    models.Index(
                        fields=["status", "severity"],
                        name="security_im_status_3fcff3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("otp", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("verification", "Verification"),
                            ("password_reset", "Password Reset"),
                            ("transaction", "Transaction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_emailotp",
                "indexes": [
                    models.Index(
                        fields=["email", "otp", "expires_at"],
                        name="security_em_email_ddfe9d_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="security_em_expires_f242d7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_documenthash",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["file_hash"], name="security_do_file_ha_410cc7_idx"
                    ),
                    models.Index(
                        fields=["-uploaded_at"], name="security_do_uploade_9695b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_plot", "Create Listing"),
                            ("edit_plot", "Edit Listing"),
                            ("delete_plot", "Delete Listing"),
                            ("verify_landowner", "Verify Landowner"),
                            ("reject_landowner", "Reject Landowner"),
                            ("verify_agent", "Verify Agent"),
                            ("verify_plot", "Verify Plot"),
                            ("reject_plot", "Reject Plot"),
                            ("change_price", "Change Price"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("document_upload", "Document Uploaded"),
                            ("document_view", "Document Viewed"),
                            ("export_data", "Data Exported"),
                            ("settings_change", "Settings Changed"),
                            ("role_assigned", "Role Assigned"),
                            ("approval_granted", "Approval Granted"),
                            ("dispute_raised", "Dispute Raised"),
                            ("dispute_resolved", "Dispute Resolved"),
                            ("two_factor_enable", "2FA Enabled"),
                            ("two_factor_disable", "2FA Disabled"),
                            ("verification_code_sent", "Verification Code Sent"),
                            (
                                "verification_code_verified",
                                "Verification Code Verified",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("old_data", models.JSONField(blank=True, default=dict)),
                ("new_data", models.JSONField(blank=True, default=dict)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                (
                    "hash_signature",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, unique=True
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_verified", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "security_auditlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="security_au_created_c66454_idx"
                    ),
                    models.Index(
                        fields=["user", "action"], name="security_au_user_id_61e86d_idx"
                    ),
                    models.Index(
                        fields=["hash_signature"], name="security_au_hash_si_94435e_idx"
                    ),
                    models.Index(
                        fields=["severity", "created_at"],
                        name="security_au_severit_5e620c_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="security_au_object__3feaba_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="security_au_created_82f799_idx"
                    ),
                ],
            },
        ),
    ]
