# Generated by Django 5.2.10 on 2026-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
