# kenya_data.py

KENYA_COUNTIES = [
    'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo Marakwet', 'Embu', 'Garissa',
    'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho', 'Kiambu', 'Kilifi',
    'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui', 'Kwale', 'Laikipia', 'Lamu',
    'Machakos', 'Makueni', 'Mandera', 'Marsabit', 'Meru', 'Migori', 'Mombasa',
    'Muranga', 'Nairobi', 'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua',
    'Nyeri', 'Samburu', 'Siaya', 'Taita Taveta', 'Tana River', 'Tharaka Nithi',
    'Trans Nzoia', 'Turkana', 'Uasin Gishu', 'Vihiga', 'Wajir', 'West Pokot'
]

# Dictionary mapping counties to their sub-counties
KENYA_SUB_COUNTIES = {
    'Baringo': ['Baringo Central', 'Baringo North', 'Baringo South', 'Eldama Ravine', 'Mogotio', 'Tiaty'],
    'Bomet': ['Bomet Central', 'Bomet East', 'Chepalungu', 'Konoin', 'Sotik'],
    'Bungoma': ['Bumula', 'Kabuchai', 'Kanduyi', 'Kimilili', 'Mt Elgon', 'Sirisia', 'Tongaren', 'Webuye East', 'Webuye West'],
    'Busia': ['Budalangi', 'Butula', 'Funyula', 'Matayos', 'Nambale', 'Teso North', 'Teso South'],
    'Elgeyo Marakwet': ['Keiyo North', 'Keiyo South', 'Marakwet East', 'Marakwet West'],
    'Embu': ['Manyatta', 'Mbeere North', 'Mbeere South', 'Runyenjes'],
    'Garissa': ['Balambala', 'Dadaab', 'Fafi', 'Garissa', 'Hulugho', 'Ijara', 'Lagdera'],
    'Homa Bay': ['Homa Bay Town', 'Kabondo Kasipul', 'Karachuonyo', 'Kasipul', 'Mbita', 'Ndhiwa', 'Rangwe', 'Suba'],
    'Isiolo': ['Isiolo North', 'Isiolo South', 'Merti'],
    'Kajiado': ['Kajiado Central', 'Kajiado East', 'Kajiado North', 'Kajiado West', 'Loitokitok', 'Mashuuru'],
    'Kakamega': ['Butere', 'Kakamega Central', 'Kakamega East', 'Kakamega North', 'Kakamega South', 'Khwisero', 'Lugari', 'Lukuyani', 'Lurambi', 'Matete', 'Mumias East', 'Mumias West', 'Navakholo'],
    'Kericho': ['Ainamoi', 'Belgut', 'Bureti', 'Kipkelion East', 'Kipkelion West', 'Soin Sigowet'],
    'Kiambu': ['Gatundu North', 'Gatundu South', 'Githunguri', 'Juja', 'Kabete', 'Kiambaa', 'Kiambu', 'Kikuyu', 'Limuru', 'Lari', 'Ruiru', 'Thika Town'],
    'Kilifi': ['Bahari', 'Ganze', 'Kaloleni', 'Kilifi North', 'Kilifi South', 'Magarini', 'Malindi', 'Rabai'],
    'Kirinyaga': ['Gichugu', 'Kirinyaga Central', 'Mwea', 'Ndia'],
    'Kisii': ['Bobasi', 'Bomachoge Borabu', 'Bomachoge Chache', 'Bonchari', 'Kitutu Chache North', 'Kitutu Chache South', 'Marani', 'Masaba North', 'Nyaribari Chache', 'Nyaribari Masaba', 'South Mugirango'],
    'Kisumu': ['Kisumu Central', 'Kisumu East', 'Kisumu West', 'Nyakach', 'Nyando', 'Seme'],
    'Kitui': ['Kitui Central', 'Kitui East', 'Kitui Rural', 'Kitui South', 'Kitui West', 'Lower Yatta', 'Matiuki', 'Mwingi Central', 'Mwingi East', 'Mwingi North', 'Mwingi West'],
    'Kwale': ['Kinango', 'Lunga Lunga', 'Matuga', 'Msambweni', 'Samburu'],
    'Laikipia': ['Laikipia Central', 'Laikipia East', 'Laikipia North', 'Laikipia West', 'Nyahururu'],
    'Lamu': ['Lamu East', 'Lamu West'],
    'Machakos': ['Kathiani', 'Machakos Town', 'Masinga', 'Matungulu', 'Mavoko', 'Mwala', 'Yatta'],
    'Makueni': ['Kaiti', 'Kibwezi East', 'Kibwezi West', 'Kilome', 'Makueni', 'Mbooni'],
    'Mandera': ['Banissa', 'Lafey', 'Mandera East', 'Mandera North', 'Mandera South', 'Mandera West'],
    'Marsabit': ['Laisamis', 'Marsabit Central', 'Marsabit North', 'Marsabit South', 'Moyale', 'North Horr', 'Saku'],
    'Meru': ['Buuri', 'Central Imenti', 'Igembe Central', 'Igembe North', 'Igembe South', 'North Imenti', 'South Imenti', 'Tigania East', 'Tigania West'],
    'Migori': ['Awendo', 'Kuria East', 'Kuria West', 'Migori', 'Nyatike', 'Rongo', 'Suna East', 'Suna West', 'Uriri'],
    'Mombasa': ['Changamwe', 'Jomvu', 'Kisauni', 'Likoni', 'Mvita', 'Nyali'],
    'Muranga': ['Gatanga', 'Kahuro', 'Kandara', 'Kangema', 'Kiharu', 'Kigumo', 'Mathioya', 'Muranga Town'],
    'Nairobi': ['Dagoretti North', 'Dagoretti South', 'Embakasi Central', 'Embakasi East', 'Embakasi North', 'Embakasi South', 'Embakasi West', 'Kamukunji', 'Kasarani', 'Kibra', 'Langata', 'Makadara', 'Mathare', 'Roysambu', 'Ruaraka', 'Starehe', 'Westlands'],
    'Nakuru': ['Bahati', 'Gilgil', 'Kuresoi North', 'Kuresoi South', 'Molo', 'Naivasha', 'Nakuru East', 'Nakuru Town East', 'Nakuru Town West', 'Njoro', 'Rongai', 'Subukia'],
    'Nandi': ['Aldai', 'Chesumei', 'Emgwen', 'Mosop', 'Namdapha', 'Tinderet'],
    'Narok': ['Narok East', 'Narok North', 'Narok South', 'Narok West', 'Transmara East', 'Transmara West'],
    'Nyamira': ['Borabu', 'Manga', 'Masaba South', 'Nyamira North', 'Nyamira South'],
    'Nyandarua': ['Kinangop', 'Kipipiri', 'Ndaragwa', 'Ol Jorok', 'Ol Kalou'],
    'Nyeri': ['Kieni East', 'Kieni West', 'Mathira East', 'Mathira West', 'Mukurweini', 'Nyeri Town', 'Othaya', 'Tetu'],
    'Samburu': ['Samburu East', 'Samburu North', 'Samburu West'],
    'Siaya': ['Alego Usonga', 'Bondo', 'Gem', 'Rarieda', 'Ugenya', 'Ugunja'],
    'Taita Taveta': ['Mwatate', 'Taveta', 'Voi', 'Wundanyi'],
    'Tana River': ['Bura', 'Galole', 'Garsen'],
    'Tharaka Nithi': ['Chuka', 'Igambangobe', 'Maara', 'Tharaka'],
    'Trans Nzoia': ['Cherangany', 'Endebess', 'Kiminini', 'Kwanza', 'Saboti'],
    'Turkana': ['Turkana Central', 'Turkana East', 'Turkana North', 'Turkana South', 'Turkana West', 'Loima'],
    'Uasin Gishu': ['Ainabkoi', 'Kapseret', 'Kesses', 'Moiben', 'Soy', 'Turbo'],
    'Vihiga': ['Emuhaya', 'Hamisi', 'Luanda', 'Sabatia', 'Vihiga'],
    'Wajir': ['Eldas', 'Tarbaj', 'Wajir East', 'Wajir North', 'Wajir South', 'Wajir West'],
    'West Pokot': ['Kipkomo', 'Pokot Central', 'Pokot North', 'Pokot South', 'West Pokot']
}