# Generated by Django 5.2.10 on 2026-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smslog",
            name="provider",
            field=models.CharField(
                choices=[("textsms", "TextSMS"), ("opensms", "OpenSMS")],
                default="textsms",
                max_length=20,
            ),
        ),
    ]
